// AI Data Center Map - Comprehensive Data (restructured April 2026)
// New template: project, company, location, lat, lng, investment, powerMW, powerGW,
// gpuModel, size, status, onlineDate, statusLabel, description, category, region, source, partner
// Merged from ai_power_dc_map_v1.0 + ai_power_dc_map_v1.1

const DATA_CENTERS = [
  {
    id: "aws-indiana",
    project: "AWS Project Rainier",
    company: "Amazon Web Services",
    location: "New Carlisle, Indiana, USA",
    lat: 41.7003,
    lng: -86.1981,
    investment: "$11B",
    powerMW: 2250,
    powerGW: 2.25,
    gpuModel: "AWS Trainium 2",
    size: "1,200 acres, 30 buildings planned",
    status: "operational",
    onlineDate: "2025-10",
    statusLabel: "Online Date: 2025-10",
    description: "Amazon's largest AI data center, 1,200 acres, 30 buildings planned. Dedicated to Anthropic AI training with 500,000+ AWS Trainium 2 chips. Operational since Oct 2025.",
    category: "hyperscaler",
    region: "north-america",
    source: "https://www.cnbc.com/2025/10/29/amazon-opens-11-billion-ai-data-center-project-rainier-in-indiana.html",
    partner: "Anthropic"
  },
  {
    id: "aws-virginia",
    project: "AWS US East",
    company: "Amazon Web Services",
    location: "Northern Virginia, USA",
    lat: 39.0438,
    lng: -77.4874,
    investment: null,
    powerMW: 800,
    powerGW: 0.8,
    gpuModel: "Mixed GPU/Trainium",
    size: null,
    status: "operational",
    onlineDate: "2020-01",
    statusLabel: "Online Date: 2020-01",
    description: "AWS's largest existing region, powering the majority of US East cloud and AI workloads. Continuously expanding.",
    category: "hyperscaler",
    region: "north-america",
    source: null,
    partner: null
  },
  {
    id: "ms-fairwater1",
    project: "Microsoft Fairwater 1",
    company: "Microsoft Azure",
    location: "Mount Pleasant, Wisconsin, USA",
    lat: 42.7261,
    lng: -87.7828,
    investment: "$7B+ (total WI commitment)",
    powerMW: 1000,
    powerGW: 1,
    gpuModel: "NVIDIA GB200/GB300",
    size: "315 acres, 1.2M sq ft, 3 buildings",
    status: "operational",
    onlineDate: "2025-09",
    statusLabel: "Online Date: 2025-09",
    description: "World's most powerful AI datacenter. Uses closed-loop liquid cooling. Connected via AI Wide Area Network. Part of $7.3B investment.",
    category: "hyperscaler",
    region: "north-america",
    source: "https://blogs.microsoft.com/on-the-issues/2025/09/18/made-in-wisconsin-the-worlds-most-powerful-ai-datacenter/",
    partner: null
  },
  {
    id: "ms-fairwater2",
    project: "Microsoft Fairwater 2",
    company: "Microsoft Azure",
    location: "Atlanta, Georgia, USA",
    lat: 33.749,
    lng: -84.388,
    investment: "Part of multi-billion $ program",
    powerMW: 1000,
    powerGW: 1,
    gpuModel: "NVIDIA GB200/GB300",
    size: null,
    status: "operational",
    onlineDate: "2025-11",
    statusLabel: "Online Date: 2025-11",
    description: "Second Fairwater site, connected to Wisconsin via dedicated fiber. Currently the world's most powerful AI facility online.",
    category: "hyperscaler",
    region: "north-america",
    source: "https://news.microsoft.com/source/features/ai/from-wisconsin-to-atlanta-microsoft-connects-datacenters-to-build-its-first-ai-superfactory/",
    partner: null
  },
  {
    id: "ms-fairwater4",
    project: "Microsoft Fairwater 4",
    company: "Microsoft Azure",
    location: "Atlanta, Georgia, USA",
    lat: 33.85,
    lng: -84.35,
    investment: "Part of multi-billion $ program",
    powerMW: 1300,
    powerGW: 1.3,
    gpuModel: "NVIDIA GB300+",
    size: null,
    status: "construction",
    onlineDate: "2027-06",
    statusLabel: "Under Construction (Planned Online: 2027-06)",
    description: "Under construction near Fairwater 2. When complete, total Fairwater network exceeds 3.3 GW by end 2027.",
    category: "hyperscaler",
    region: "north-america",
    source: "https://news.microsoft.com/source/features/ai/from-wisconsin-to-atlanta-microsoft-connects-datacenters-to-build-its-first-ai-superfactory/",
    partner: null
  },
  {
    id: "gcp-detroit",
    project: "Google Detroit AI Campus",
    company: "Google Cloud",
    location: "Detroit, Michigan, USA",
    lat: 42.3314,
    lng: -83.0458,
    investment: null,
    powerMW: 2700,
    powerGW: 2.7,
    gpuModel: "Google TPU v6",
    size: null,
    status: "construction",
    onlineDate: "2027-01",
    statusLabel: "Under Construction (Planned Online: 2027-01)",
    description: "Massive new campus powered by 2.7 GW of new resources via Xcel Energy partnership. Includes 1.6 GW solar, 400 MW storage.",
    category: "hyperscaler",
    region: "north-america",
    source: null,
    partner: null
  },
  {
    id: "gcp-iowa",
    project: "Google Council Bluffs",
    company: "Google Cloud",
    location: "Council Bluffs, Iowa, USA",
    lat: 41.2619,
    lng: -95.8608,
    investment: null,
    powerMW: 400,
    powerGW: 0.4,
    gpuModel: "Google TPU v5/v6",
    size: null,
    status: "operational",
    onlineDate: "2009-01",
    statusLabel: "Online Date: 2009-01",
    description: "One of Google's largest and longest-running data centers. Over $5.5B invested. 100+ MW with continuous expansions.",
    category: "hyperscaler",
    region: "north-america",
    source: null,
    partner: null
  },
  {
    id: "gcp-nevada",
    project: "Google Nevada Campus",
    company: "Google Cloud",
    location: "Nevada, USA",
    lat: 36.1699,
    lng: -115.1398,
    investment: null,
    powerMW: 500,
    powerGW: 0.5,
    gpuModel: "Google TPU v6",
    size: null,
    status: "construction",
    onlineDate: "2026-06",
    statusLabel: "Under Construction (Planned Online: 2026-06)",
    description: "New AI campus with clean energy partnership through AES. Part of Google's strategy to bring 9+ GW of new electricity capacity.",
    category: "hyperscaler",
    region: "north-america",
    source: null,
    partner: null
  },
  {
    id: "meta-hyperion",
    project: "Meta Hyperion",
    company: "Meta Platforms",
    location: "Richland Parish, Louisiana, USA",
    lat: 32.02,
    lng: -91.88,
    investment: "$10B–$50B (phased)",
    powerMW: 5000,
    powerGW: 5,
    gpuModel: "NVIDIA GB200/GB300",
    size: "4M+ sq ft on 3,650+ acres (expanding)",
    status: "construction",
    onlineDate: "2026-05",
    statusLabel: "Under Construction (Planned Online: 2026-05)",
    description: "Largest planned data center in the Western Hemisphere. 3,650 acres. 10 gas power plants (7.5 GW) + 2.5 GW renewables. $27B total via Blue Owl Capital JV. Phase 1: 2 GW.",
    category: "hyperscaler",
    region: "north-america",
    source: "https://fortune.com/2026/02/04/meta-hyperion-ai-data-center-louisiana-expansion/",
    partner: "Entergy, Blue Owl Capital"
  },
  {
    id: "oci-abilene",
    project: "Oracle Stargate Abilene",
    company: "Oracle Cloud",
    location: "Abilene, Texas, USA",
    lat: 32.4487,
    lng: -99.7331,
    investment: "$500B (overall program)",
    powerMW: 1200,
    powerGW: 1.2,
    gpuModel: "NVIDIA GB200",
    size: "4,000,000 sq ft",
    status: "operational",
    onlineDate: "2025-06",
    statusLabel: "Online Date: 2025-06",
    description: "Flagship Stargate campus, operational on Oracle Cloud Infrastructure. First NVIDIA GB200 racks delivered June 2025. Scaling from 200 MW to 1.2 GW.",
    category: "hyperscaler",
    region: "north-america",
    source: "https://openai.com/index/five-new-stargate-sites/",
    partner: "OpenAI, SoftBank"
  },
  {
    id: "oci-shackelford",
    project: "Oracle Stargate Shackelford",
    company: "Oracle Cloud",
    location: "Shackelford County, Texas, USA",
    lat: 32.72,
    lng: -99.35,
    investment: "$25B",
    powerMW: 2000,
    powerGW: 2,
    gpuModel: "NVIDIA GB200+",
    size: "3,700,000 sq ft",
    status: "construction",
    onlineDate: "2027-01",
    statusLabel: "Under Construction (Planned Online: 2027-01)",
    description: "New Stargate site developed by Oracle. Part of 5.5 GW Oracle-OpenAI expansion. Multiple gigawatts planned.",
    category: "hyperscaler",
    region: "north-america",
    source: "https://www.equipmentworld.com/market-pulse/article/15816534/data-center-construction-boom-to-grow-in-2026",
    partner: "OpenAI"
  },
  {
    id: "oci-newmexico",
    project: "Oracle Stargate New Mexico",
    company: "Oracle Cloud",
    location: "Doña Ana County, New Mexico, USA",
    lat: 32.35,
    lng: -106.75,
    investment: null,
    powerMW: 1500,
    powerGW: 1.5,
    gpuModel: "NVIDIA GB200+",
    size: null,
    status: "construction",
    onlineDate: "2027-06",
    statusLabel: "Under Construction (Planned Online: 2027-06)",
    description: "New Stargate data center site. Part of the $300B+ Oracle-OpenAI partnership over five years.",
    category: "hyperscaler",
    region: "north-america",
    source: "https://openai.com/index/five-new-stargate-sites/",
    partner: "OpenAI"
  },
  {
    id: "oci-wisconsin",
    project: "Oracle Stargate Wisconsin",
    company: "Oracle Cloud",
    location: "Wisconsin, USA",
    lat: 43.0389,
    lng: -87.9065,
    investment: "$15B+",
    powerMW: 800,
    powerGW: 0.8,
    gpuModel: "NVIDIA GB200+",
    size: "2,500,000 sq ft across 672 acres",
    status: "construction",
    onlineDate: "2027-03",
    statusLabel: "Under Construction (Planned Online: 2027-03)",
    description: "Midwest Stargate site, developed by Oracle in partnership with Vantage.",
    category: "hyperscaler",
    region: "north-america",
    source: "https://vantage-dc.com/data-center-locations/north-america/port-washington-wisconsin",
    partner: "OpenAI, Vantage"
  },
  {
    id: "alibaba-zhangbei",
    project: "Alibaba Cloud Zhangbei",
    company: "Alibaba Cloud",
    location: "Zhangbei County, Hebei, China",
    lat: 41.15,
    lng: 114.7,
    investment: null,
    powerMW: 150,
    powerGW: 0.15,
    gpuModel: "Mixed",
    size: null,
    status: "operational",
    onlineDate: "2018-01",
    statusLabel: "Online Date: 2018-01",
    description: "One of Asia's largest data center campuses. 667,972 sqm, 52 buildings, 50,000 data racks. Over $2.9B invested.",
    category: "hyperscaler",
    region: "asia-pacific",
    source: null,
    partner: null
  },
  {
    id: "ibm-langfang",
    project: "IBM/Range Information Hub",
    company: "IBM Cloud",
    location: "Langfang, Hebei, China",
    lat: 39.5,
    lng: 116.68,
    investment: null,
    powerMW: 150,
    powerGW: 0.15,
    gpuModel: "Mixed",
    size: null,
    status: "operational",
    onlineDate: "2016-01",
    statusLabel: "Online Date: 2016-01",
    description: "Range International Information Hub built with IBM. 585,000 sqm. $3B investment. Supports government & enterprise AI/cloud.",
    category: "hyperscaler",
    region: "asia-pacific",
    source: null,
    partner: null
  },
  {
    id: "huawei-guian",
    project: "Huawei Gui'an Cloud DC",
    company: "Huawei",
    location: "Gui'an New Area, Guizhou, China",
    lat: 26.42,
    lng: 106.65,
    investment: null,
    powerMW: 200,
    powerGW: 0.2,
    gpuModel: "Huawei Ascend",
    size: null,
    status: "operational",
    onlineDate: "2021-01",
    statusLabel: "Online Date: 2021-01",
    description: "Huawei's major cloud data center in southwestern China. Supports Huawei Cloud AI and enterprise services across Asia-Pacific.",
    category: "hyperscaler",
    region: "asia-pacific",
    source: null,
    partner: null
  },
  {
    id: "nebius-independence",
    project: "Nebius Independence AI Factory",
    company: "Nebius",
    location: "Independence, Missouri, USA",
    lat: 39.0836,
    lng: -94.3543,
    investment: null,
    powerMW: 1200,
    powerGW: 1.2,
    gpuModel: "NVIDIA GB200/GB300",
    size: null,
    status: "construction",
    onlineDate: "2028-01",
    statusLabel: "Under Construction (Planned Online: 2028-01)",
    description: "Nebius's largest US AI factory. City Council approved Mar 2026. Up to 1.2 GW capacity across 400 acres, 10+ buildings. $6.6B investment. New 250 MW power plant expanding to 1,100 MW by 2029. Construction starts summer 2026, completion expected 2028.",
    category: "neocloud",
    region: "north-america",
    source: null,
    partner: null
  },
  {
    id: "nebius-kc",
    project: "Nebius Kansas City",
    company: "Nebius",
    location: "Kansas City, Missouri, USA",
    lat: 39.0997,
    lng: -94.5786,
    investment: null,
    powerMW: 40,
    powerGW: 0.04,
    gpuModel: "NVIDIA Blackwell",
    size: null,
    status: "operational",
    onlineDate: "2025-01",
    statusLabel: "Online Date: 2025-01",
    description: "US gateway facility. 5 MW live (Q1 2025), expanding to 40 MW. Anchor tenant at Patmos AI Campus. Supports enterprise inference workloads.",
    category: "neocloud",
    region: "north-america",
    source: null,
    partner: null
  },
  {
    id: "nebius-vineland",
    project: "Nebius New Jersey (Vineland)",
    company: "Nebius",
    location: "Vineland, New Jersey, USA",
    lat: 39.4863,
    lng: -75.026,
    investment: "$1.8B",
    powerMW: 300,
    powerGW: 0.3,
    gpuModel: "NVIDIA Blackwell",
    size: "392,600 sq ft",
    status: "operational",
    onlineDate: "2025-06",
    statusLabel: "Online Date: 2025-06",
    description: "First major US AI data center. ~2.6M sqft. Built by DataOne with Nebius-designed infrastructure. Behind-the-meter islanded microgrid. 300-400 MW capacity. $17B Microsoft contract. 3+ data rooms operational. Liquid-cooled, 100+ kW/rack.",
    category: "neocloud",
    region: "north-america",
    source: "https://re-nj.com/coreweave-begins-1-8-billion-data-center-project-in-kenilworth-landing-first-award-under-new-eda-tax-credit-program/",
    partner: "DataOne, Microsoft"
  },
  {
    id: "nebius-birmingham",
    project: "Nebius Birmingham BHM01",
    company: "Nebius",
    location: "Birmingham, Alabama, USA",
    lat: 33.5207,
    lng: -86.8025,
    investment: null,
    powerMW: 300,
    powerGW: 0.3,
    gpuModel: "NVIDIA Blackwell",
    size: null,
    status: "planned",
    onlineDate: "2027-01",
    statusLabel: "Planned Capacity Date: 2027-01",
    description: "Southeast US anchor site. Phased development toward ~300 MW total campus capacity on 80-acre site in Oxmoor area. Brownfield-to-AI-factory conversion. Permitting underway.",
    category: "neocloud",
    region: "north-america",
    source: null,
    partner: null
  },
  {
    id: "nebius-minnesota",
    project: "Nebius Minnesota",
    company: "Nebius",
    location: "Minneapolis, Minnesota, USA",
    lat: 44.9778,
    lng: -93.265,
    investment: "$1B+",
    powerMW: 100,
    powerGW: 0.1,
    gpuModel: "NVIDIA GPU",
    size: null,
    status: "planned",
    onlineDate: "2027-01",
    statusLabel: "Planned Capacity Date: 2027-01",
    description: "Planned US expansion site in Minneapolis area. Part of Nebius's goal to reach 16 global data center locations by end of 2026.",
    category: "neocloud",
    region: "north-america",
    source: "https://www.crn.com/news/cloud/2026/google-unveils-two-new-us-data-centers-as-185-billion-commitment-gets-underway",
    partner: null
  },
  {
    id: "nebius-oklahoma",
    project: "Nebius Oklahoma",
    company: "Nebius",
    location: "Oklahoma, USA",
    lat: 35.4676,
    lng: -97.5164,
    investment: null,
    powerMW: 100,
    powerGW: 0.1,
    gpuModel: "NVIDIA GPU",
    size: null,
    status: "planned",
    onlineDate: "2027-01",
    statusLabel: "Planned Capacity Date: 2027-01",
    description: "Planned US expansion site. Part of Nebius's strategy to establish 16 global data center locations by end of 2026.",
    category: "neocloud",
    region: "north-america",
    source: null,
    partner: null
  },
  {
    id: "nebius-mantsala",
    project: "Nebius Mäntsälä",
    company: "Nebius",
    location: "Mäntsälä, Finland",
    lat: 60.6358,
    lng: 25.5181,
    investment: null,
    powerMW: 75,
    powerGW: 0.075,
    gpuModel: "NVIDIA H100/H200/Blackwell",
    size: null,
    status: "operational",
    onlineDate: "2014-01",
    statusLabel: "Online Date: 2014-01",
    description: "Nebius's flagship European data center since 2014. Tripled to 75 MW capacity. Hosts ISEG supercomputer (16th on Top500). Exports heat to local district heating. Up to 60,000 GPUs. Part of Meta contract. 100% renewable energy.",
    category: "neocloud",
    region: "europe",
    source: null,
    partner: null
  },
  {
    id: "nebius-lappeenranta",
    project: "Nebius Lappeenranta",
    company: "Nebius",
    location: "Lappeenranta, Finland",
    lat: 61.0587,
    lng: 28.1887,
    investment: null,
    powerMW: 310,
    powerGW: 0.31,
    gpuModel: "NVIDIA GPU",
    size: null,
    status: "construction",
    onlineDate: "2027-01",
    statusLabel: "Under Construction (Planned Online: 2027-01)",
    description: "Nebius's largest facility outside the US. 310 MW AI data center campus. $10B+ estimated value. Built by Polarnode. Covers ~10% of Nebius's contracted capacity. One of Europe's largest AI-dedicated facilities. Phased delivery from 2027.",
    category: "neocloud",
    region: "europe",
    source: null,
    partner: null
  },
  {
    id: "nebius-bethune",
    project: "Nebius Béthune (Lille)",
    company: "Nebius",
    location: "Béthune, Pas-de-Calais, France",
    lat: 50.5299,
    lng: 2.6408,
    investment: null,
    powerMW: 240,
    powerGW: 0.24,
    gpuModel: "NVIDIA Blackwell",
    size: null,
    status: "construction",
    onlineDate: "2026-12",
    statusLabel: "Under Construction (Planned Online: 2026-12)",
    description: "One of Europe's largest AI factories. 240 MW on former Bridgestone tyre plant site. 26,000 sqm. Phase 1 late summer 2026, ~120 MW by end 2026, full 240 MW by end 2027. 132-142 kW/rack, Blackwell NVL72 optimized. Colocation with Azur Datacenter.",
    category: "neocloud",
    region: "europe",
    source: null,
    partner: null
  },
  {
    id: "nebius-paris",
    project: "Nebius Paris (Equinix PA10)",
    company: "Nebius",
    location: "Saint-Denis, Paris, France",
    lat: 48.9362,
    lng: 2.3574,
    investment: "$20.7B",
    powerMW: 10,
    powerGW: 0.01,
    gpuModel: "NVIDIA H200",
    size: null,
    status: "operational",
    onlineDate: "2024-11",
    statusLabel: "Online Date: 2024-11",
    description: "Colocation at Equinix PA10 campus in Saint-Denis. First European site with NVIDIA H200 Tensor Core GPUs. First facility equipped solely with Nebius-designed servers.",
    category: "neocloud",
    region: "europe",
    source: "https://www.sentisight.ai/european-countries-with-most-data-centers/",
    partner: null
  },
  {
    id: "nebius-longcross",
    project: "Nebius UK (Longcross)",
    company: "Nebius",
    location: "Longcross Park, Surrey, UK",
    lat: 51.3838,
    lng: -0.5786,
    investment: null,
    powerMW: 16,
    powerGW: 0.016,
    gpuModel: "NVIDIA Blackwell Ultra",
    size: null,
    status: "operational",
    onlineDate: "2025-11",
    statusLabel: "Online Date: 2025-11",
    description: "Nebius's first UK data center at Ark Data Centres' Longcross Park. 3 data halls, 126 racks, 16 MW. 11 PB storage. NVIDIA Blackwell Ultra GPUs. Advanced liquid cooling, low-latency InfiniBand Q-X800 networking.",
    category: "neocloud",
    region: "europe",
    source: null,
    partner: "Ark Data Centres"
  },
  {
    id: "nebius-keflavik",
    project: "Nebius Keflavik (Iceland)",
    company: "Nebius",
    location: "Keflavik, Iceland",
    lat: 63.9993,
    lng: -22.5558,
    investment: null,
    powerMW: 10,
    powerGW: 0.01,
    gpuModel: "NVIDIA GPU",
    size: null,
    status: "operational",
    onlineDate: "2025-06",
    statusLabel: "Online Date: 2025-06",
    description: "Colocation with Verne in Keflavik. 10 MW compute cluster. 100% renewable hydroelectric and geothermal energy. Natural cooling advantages in subarctic climate.",
    category: "neocloud",
    region: "europe",
    source: null,
    partner: "Verne"
  },
  {
    id: "nebius-modiin",
    project: "Nebius Modi'in (Israel)",
    company: "Nebius",
    location: "Modi'in, Israel",
    lat: 31.8928,
    lng: 34.8713,
    investment: null,
    powerMW: 8,
    powerGW: 0.008,
    gpuModel: "NVIDIA B200",
    size: null,
    status: "operational",
    onlineDate: "2025-09",
    statusLabel: "Online Date: 2025-09",
    description: "8 MW colocation at Mega Or/Mega DC facility. Deployed 4,000 NVIDIA GPUs. Hosts part of Israel's national supercomputer via Israel Innovation Authority. Expanding with 80 MW across Masmiyya (22 MW) and Beit Shemesh (58 MW).",
    category: "neocloud",
    region: "middle-east",
    source: null,
    partner: "Mega Or/Mega DC"
  },
  {
    id: "nebius-israel-expansion",
    project: "Nebius Israel Expansion",
    company: "Nebius",
    location: "Masmiyya & Beit Shemesh, Israel",
    lat: 31.7167,
    lng: 34.9875,
    investment: null,
    powerMW: 80,
    powerGW: 0.08,
    gpuModel: "NVIDIA GPU",
    size: null,
    status: "construction",
    onlineDate: "2026-09",
    statusLabel: "Under Construction (Planned Online: 2026-09)",
    description: "Major 80 MW expansion across two Mega Or sites: 22 MW in Masmiyya, 58 MW in Beit Shemesh. $880M investment. 5-year lease. Expandable to 64 MW (Masmiyya) and 222 MW (Beit Shemesh). Delivery Q3 2026 through Q1 2027.",
    category: "neocloud",
    region: "middle-east",
    source: null,
    partner: "Mega Or/Mega DC"
  },
  {
    id: "coreweave-us",
    project: "CoreWeave US Network",
    company: "CoreWeave",
    location: "Multiple US locations",
    lat: 40.7128,
    lng: -74.006,
    investment: "$1.8B",
    powerMW: 850,
    powerGW: 0.85,
    gpuModel: "NVIDIA H100/GB200",
    size: "392,600 sq ft",
    status: "operational",
    onlineDate: "2025-12",
    statusLabel: "Online Date: 2025-12",
    description: "43 data centers with 850 MW active power (end 2025). Added 250 MW in Q4 2025 alone. Targeting 5 GW additional by 2030. Over 3 GW contracted.",
    category: "neocloud",
    region: "north-america",
    source: "https://re-nj.com/coreweave-begins-1-8-billion-data-center-project-in-kenilworth-landing-first-award-under-new-eda-tax-credit-program/",
    partner: null
  },
  {
    id: "coreweave-hammond",
    project: "CoreWeave Hammond",
    company: "CoreWeave",
    location: "Hammond, Indiana, USA",
    lat: 41.6142,
    lng: -87.4973,
    investment: null,
    powerMW: 180,
    powerGW: 0.18,
    gpuModel: "NVIDIA GPU",
    size: null,
    status: "planned",
    onlineDate: "2027-12",
    statusLabel: "Planned Capacity Date: 2027-12",
    description: "180 MW AI data center at the Digital Crossroads campus (301 Digital Crossroads Dr). 450,000 sq ft on 25-acre site at former State Line Generating Plant. Developed with Decennial Group under a 20-year lease. Announced Jun 2025, operational target 2027 pending NIPSCO power agreement.",
    category: "neocloud",
    region: "north-america",
    source: null,
    partner: null
  },
  {
    id: "coreweave-kenilworth",
    project: "CoreWeave Kenilworth",
    company: "CoreWeave",
    location: "Kenilworth, New Jersey, USA",
    lat: 40.6798,
    lng: -74.2946,
    investment: "$1.8B",
    powerMW: 100,
    powerGW: 0.1,
    gpuModel: "NVIDIA GPU",
    size: "392,600 sq ft",
    status: "planned",
    onlineDate: "2026-12",
    statusLabel: "Planned Capacity Date: 2026-12",
    description: "AI data center at Northeast Science & Technology Center (2000 Galloping Hill Rd). 280,000 sq ft with over $1.2 billion committed. PSE&G upgrading local electrical infrastructure to support facility. Planned status per datacentermap.",
    category: "neocloud",
    region: "north-america",
    source: "https://re-nj.com/coreweave-begins-1-8-billion-data-center-project-in-kenilworth-landing-first-award-under-new-eda-tax-credit-program/",
    partner: null
  },
  {
    id: "coreweave-lancaster",
    project: "CoreWeave Lancaster",
    company: "CoreWeave",
    location: "Lancaster, Pennsylvania, USA",
    lat: 40.0379,
    lng: -76.3055,
    investment: "Up to $6B",
    powerMW: 400,
    powerGW: 0.4,
    gpuModel: "NVIDIA GPU",
    size: null,
    status: "planned",
    onlineDate: "2027-12",
    statusLabel: "Planned Capacity Date: 2027-12",
    description: "$6 billion AI data center campus at 216 Greenfield Rd. Former printing press facilities totaling 2M+ sq ft across 144 acres being converted by Machine Investment Group. Co-funded by Blue Owl Capital and Chirisa Technology Parks. Announced Jul 2025 as one of CoreWeave's largest campus developments.",
    category: "neocloud",
    region: "north-america",
    source: "https://investors.coreweave.com/news/news-details/2025/CoreWeave-Announces-Multi-Billion-Dollar-Commitment-to-AI-Infrastructure-in-Pennsylvania/default.aspx",
    partner: null
  },
  {
    id: "coreweave-plano",
    project: "CoreWeave Plano",
    company: "CoreWeave",
    location: "Plano, Texas, USA",
    lat: 33.0635,
    lng: -96.7495,
    investment: "Part of $50B plan",
    powerMW: 30,
    powerGW: 0.03,
    gpuModel: "NVIDIA GPU",
    size: null,
    status: "operational",
    onlineDate: "2023-12",
    statusLabel: "Online Date: 2023-12",
    description: "30 MW AI data center at Lincoln Rackhouse's 1000 Coit Rd building. 454,421 sq ft on 23.8-acre campus. $1.6 billion investment with 6-year Master Services Agreement. Four 14,000 sq ft data halls plus 50,000 sq ft powered shell space. Operational since end of 2023.",
    category: "neocloud",
    region: "north-america",
    source: "https://www.datacenterknowledge.com/data-center-construction/new-data-center-developments-december-2025",
    partner: null
  },
  {
    id: "iren-childress",
    project: "IREN Horizon 1 (Childress)",
    company: "IREN",
    location: "Childress, Texas, USA",
    lat: 34.4265,
    lng: -100.204,
    investment: null,
    powerMW: 75,
    powerGW: 0.075,
    gpuModel: "NVIDIA Blackwell",
    size: null,
    status: "operational",
    onlineDate: "2025-12",
    statusLabel: "Online Date: 2025-12",
    description: "75 MW liquid-cooled AI/HPC data center. 200kW per rack via direct-to-chip cooling for NVIDIA Blackwell. Part of 750 MW Childress campus.",
    category: "neocloud",
    region: "north-america",
    source: null,
    partner: null
  },
  {
    id: "iren-sweetwater1",
    project: "IREN Sweetwater 1",
    company: "IREN",
    location: "Fisher County, Texas, USA",
    lat: 32.47,
    lng: -100.4,
    investment: "$500B (overall program)",
    powerMW: 1400,
    powerGW: 1.4,
    gpuModel: "NVIDIA Blackwell/Next-gen",
    size: "4,000,000 sq ft",
    status: "construction",
    onlineDate: "2026-04",
    statusLabel: "Under Construction (Planned Online: 2026-04)",
    description: "1.4 GW site on track for energization April 2026. Combined with Sweetwater 2, totals 2 GW. 100% renewable energy.",
    category: "neocloud",
    region: "north-america",
    source: "https://openai.com/index/five-new-stargate-sites/",
    partner: null
  },
  {
    id: "iren-sweetwater2",
    project: "IREN Sweetwater 2",
    company: "IREN",
    location: "Fisher County, Texas, USA",
    lat: 32.5,
    lng: -100.45,
    investment: "$500B (overall program)",
    powerMW: 600,
    powerGW: 0.6,
    gpuModel: "Next-gen",
    size: "4,000,000 sq ft",
    status: "planned",
    onlineDate: "2028-01",
    statusLabel: "Planned Capacity Date: 2028-01",
    description: "600 MW expansion site. Energization expected 2028. Direct fiber loop to Sweetwater 1. Total portfolio: 4.5 GW.",
    category: "neocloud",
    region: "north-america",
    source: "https://openai.com/index/five-new-stargate-sites/",
    partner: null
  },
  {
    id: "iren-prince-george",
    project: "IREN Prince George",
    company: "IREN",
    location: "Prince George, British Columbia, Canada",
    lat: 53.917,
    lng: -122.7497,
    investment: null,
    powerMW: 50,
    powerGW: 0.05,
    gpuModel: "NVIDIA GPU",
    size: null,
    status: "operational",
    onlineDate: "2023-01",
    statusLabel: "Online Date: 2023-01",
    description: "50 MW operational data center on a 12-acre freehold site (1144 Crocker Road). Powered entirely by BC Hydro renewable hydroelectricity. Supports 20+ full-time local jobs. Largest city in northern BC.",
    category: "neocloud",
    region: "north-america",
    source: null,
    partner: null
  },
  {
    id: "iren-mackenzie",
    project: "IREN Mackenzie",
    company: "IREN",
    location: "Mackenzie, British Columbia, Canada",
    lat: 55.2978,
    lng: -123.0915,
    investment: null,
    powerMW: 80,
    powerGW: 0.08,
    gpuModel: "NVIDIA GPU",
    size: null,
    status: "operational",
    onlineDate: "2022-01",
    statusLabel: "Online Date: 2022-01",
    description: "80 MW operational data center on an 11-acre freehold site (4900 Coquawaldy Rd). Powered by BC Hydro renewable hydroelectricity. Supports ~15 full-time jobs in a community historically impacted by mill closures.",
    category: "neocloud",
    region: "north-america",
    source: null,
    partner: null
  },
  {
    id: "iren-canal-flats",
    project: "IREN Canal Flats",
    company: "IREN",
    location: "Canal Flats, British Columbia, Canada",
    lat: 50.15,
    lng: -115.77,
    investment: null,
    powerMW: 30,
    powerGW: 0.03,
    gpuModel: "NVIDIA GPU",
    size: null,
    status: "operational",
    onlineDate: "2021-01",
    statusLabel: "Online Date: 2021-01",
    description: "30 MW operational data center on a 10-acre freehold site in the Canadian Rockies (9018 Grainger Rd). Connected to BC Hydro via IREN-owned 69kV substation. Dual fiber paths. Fabrication workshop supporting other IREN facilities.",
    category: "neocloud",
    region: "north-america",
    source: null,
    partner: null
  },
  {
    id: "apld-deltaforge",
    project: "Applied Digital Delta Forge 1",
    company: "Applied Digital",
    location: "Southern US",
    lat: 32.5,
    lng: -90,
    investment: null,
    powerMW: 430,
    powerGW: 0.43,
    gpuModel: "NVIDIA GPU",
    size: null,
    status: "construction",
    onlineDate: "2027-06",
    statusLabel: "Under Construction (Planned Online: 2027-06)",
    description: "430 MW AI Factory campus. Broke ground Jan 2026. Two 150 MW facilities across 500+ acres. Named Best Data Center in Americas 2025.",
    category: "neocloud",
    region: "north-america",
    source: null,
    partner: null
  },
  {
    id: "apld-polaris-forge1",
    project: "Applied Digital Polaris Forge 1",
    company: "Applied Digital",
    location: "Ellendale, North Dakota, USA",
    lat: 46.0006,
    lng: -98.525,
    investment: null,
    powerMW: 180,
    powerGW: 0.18,
    gpuModel: "NVIDIA GPU",
    size: null,
    status: "operational",
    onlineDate: "2025-12",
    statusLabel: "Online Date: 2025-12",
    description: "Ellendale AI/HPC campus listing (Site Code ELN). 180 MW capacity with liquid-cooling design. Datacentermap timeline notes first building reached operational stage in Dec 2025.",
    category: "neocloud",
    region: "north-america",
    source: null,
    partner: "CoreWeave"
  },
  {
    id: "apld-polaris-forge2",
    project: "Applied Digital Polaris Forge 2",
    company: "Applied Digital",
    location: "Harwood (Fargo area), North Dakota, USA",
    lat: 46.983,
    lng: -96.889,
    investment: null,
    powerMW: 280,
    powerGW: 0.28,
    gpuModel: "NVIDIA GPU",
    size: null,
    status: "planned",
    onlineDate: "2026-12",
    statusLabel: "Planned Capacity Date: 2026-12",
    description: "Planned AI-focused campus near Harwood in Cass County. Datacentermap lists up to 280 MW with phased launch and full buildout expected by early 2027.",
    category: "neocloud",
    region: "north-america",
    source: null,
    partner: null
  },
  {
    id: "crusoe-texas",
    project: "Crusoe AI Data Center",
    company: "Crusoe Energy",
    location: "West Texas, USA",
    lat: 32,
    lng: -100.5,
    investment: "$500B (overall program)",
    powerMW: 200,
    powerGW: 0.2,
    gpuModel: "NVIDIA H100/GB200",
    size: "4,000,000 sq ft",
    status: "construction",
    onlineDate: "2026-06",
    statusLabel: "Under Construction (Planned Online: 2026-06)",
    description: "AI cloud powered by stranded energy. Stargate partner. Uses flared natural gas and renewable sources for carbon-reduced AI compute.",
    category: "neocloud",
    region: "north-america",
    source: "https://openai.com/index/five-new-stargate-sites/",
    partner: null
  },
  {
    id: "lambda-chicago",
    project: "Lambda AI Factory Chicago",
    company: "Lambda Labs",
    location: "Chicago, Illinois, USA",
    lat: 41.8781,
    lng: -87.6298,
    investment: null,
    powerMW: 23,
    powerGW: 0.023,
    gpuModel: "NVIDIA GB200",
    size: null,
    status: "construction",
    onlineDate: "2026-06",
    statusLabel: "Under Construction (Planned Online: 2026-06)",
    description: "23 MW single-tenant AI factory built with EdgeConneX. Hybrid cooling for AI training and inference. Part of 30+ MW dual-city expansion.",
    category: "neocloud",
    region: "north-america",
    source: null,
    partner: null
  },
  {
    id: "lambda-dallas",
    project: "Lambda Cloud Dallas",
    company: "Lambda Labs",
    location: "Plano, Texas, USA",
    lat: 33.0198,
    lng: -96.6989,
    investment: "Part of $50B plan",
    powerMW: 50,
    powerGW: 0.05,
    gpuModel: "NVIDIA GB200",
    size: null,
    status: "construction",
    onlineDate: "2026-10",
    statusLabel: "Under Construction (Planned Online: 2026-10)",
    description: "Taking capacity at Aligned Data Center DFW-04. 425,500 sqft. DeltaFlow liquid cooling up to 300 kW/rack. Vision: 3 GW+ total.",
    category: "neocloud",
    region: "north-america",
    source: "https://www.datacenterknowledge.com/data-center-construction/new-data-center-developments-december-2025",
    partner: null
  },
  {
    id: "lambda-kansascity",
    project: "Lambda Kansas City",
    company: "Lambda Labs",
    location: "Kansas City, Missouri, USA",
    lat: 39.3045,
    lng: -94.7136,
    investment: null,
    powerMW: 24,
    powerGW: 0.024,
    gpuModel: "NVIDIA GPU",
    size: null,
    status: "planned",
    onlineDate: "2026-03",
    statusLabel: "Planned Capacity Date: 2026-03",
    description: "Lambda facility at 11155 N Airworld Dr. Datacentermap notes first phase announced at 24 MW with launch targeted for early 2026.",
    category: "neocloud",
    region: "north-america",
    source: null,
    partner: null
  },
  {
    id: "nscale-glomfjord",
    project: "Nscale Glomfjord",
    company: "Nscale",
    location: "Glomfjord, Norway",
    lat: 66.81,
    lng: 14.1,
    investment: null,
    powerMW: 60,
    powerGW: 0.06,
    gpuModel: "NVIDIA H100/Blackwell",
    size: null,
    status: "operational",
    onlineDate: "2024-06",
    statusLabel: "Online Date: 2024-06",
    description: "Located in Norway's Arctic Circle. 100% renewable energy. 30 MW operational, expandable to 60 MW. Best-in-class efficiency.",
    category: "neocloud",
    region: "europe",
    source: null,
    partner: null
  },
  {
    id: "nscale-narvik",
    project: "Nscale Stargate Norway (Narvik)",
    company: "Nscale",
    location: "Narvik, Norway",
    lat: 68.42,
    lng: 17.43,
    investment: null,
    powerMW: 520,
    powerGW: 0.52,
    gpuModel: "NVIDIA GB200",
    size: null,
    status: "construction",
    onlineDate: "2026-12",
    statusLabel: "Under Construction (Planned Online: 2026-12)",
    description: "Stargate Norway - AI Gigafactory. 230 MW initial + 290 MW expansion. Partnership with Aker ASA & OpenAI. $6.2B Microsoft agreement. 100,000 NVIDIA GPUs by end 2026. Powered by renewable hydropower.",
    category: "neocloud",
    region: "europe",
    source: null,
    partner: "Aker ASA, OpenAI, Microsoft"
  },
  {
    id: "nscale-sines",
    project: "Nscale Sines",
    company: "Nscale",
    location: "Sines, Portugal",
    lat: 37.9568,
    lng: -8.8677,
    investment: null,
    powerMW: 1000,
    powerGW: 1,
    gpuModel: "NVIDIA GPU",
    size: null,
    status: "construction",
    onlineDate: "2027-06",
    statusLabel: "Under Construction (Planned Online: 2027-06)",
    description: "Hyperscale site at Start Campus. GW-scale AI deployments. Seawater cooling. Trans-Atlantic low-latency hub. 100% renewable energy.",
    category: "neocloud",
    region: "europe",
    source: null,
    partner: null
  },
  {
    id: "nscale-wardcounty",
    project: "Nscale Ward County",
    company: "Nscale",
    location: "Ward County, Texas, USA",
    lat: 31.5,
    lng: -103.1,
    investment: null,
    powerMW: 1200,
    powerGW: 1.2,
    gpuModel: "NVIDIA GPU",
    size: null,
    status: "construction",
    onlineDate: "2027-01",
    statusLabel: "Under Construction (Planned Online: 2027-01)",
    description: "240 MW initial, expanding to 1.2 GW. Partnership with Ionic Digital. Direct-liquid cooling and rear-door heat-exchangers.",
    category: "neocloud",
    region: "north-america",
    source: null,
    partner: "Ionic Digital"
  },
  {
    id: "nscale-loughton",
    project: "Nscale Loughton",
    company: "Nscale",
    location: "Loughton, Essex, UK",
    lat: 51.647,
    lng: 0.055,
    investment: null,
    powerMW: 50,
    powerGW: 0.05,
    gpuModel: "NVIDIA GB200",
    size: null,
    status: "planned",
    onlineDate: "2026-10",
    statusLabel: "Planned Capacity Date: 2026-10",
    description: "Nscale's first UK site at Langston Road. Datacentermap describes 50 MW initial AI/HPC capacity with expansion potential to 90 MW and go-live target in Q4 2026.",
    category: "neocloud",
    region: "europe",
    source: null,
    partner: null
  },
  {
    id: "xai-colossus",
    project: "xAI Colossus",
    company: "xAI",
    location: "Memphis, Tennessee, USA",
    lat: 35.1495,
    lng: -90.049,
    investment: "$18B (GPU purchase alone)",
    powerMW: 2000,
    powerGW: 2,
    gpuModel: "NVIDIA GB200/GB300",
    size: "3 buildings + gas power plant",
    status: "operational",
    onlineDate: "2025-12",
    statusLabel: "Online Date: 2025-12",
    description: "World's largest single-site AI training installation. 555,000+ NVIDIA GPUs ($18B). 3 buildings: Colossus 1 (500 MW), Colossus 2 (1 GW), Building 3 'MACROHARDRR' (500 MW). On-site gas power plant in Mississippi.",
    category: "ai-independent",
    region: "north-america",
    source: "https://introl.com/blog/xai-colossus-2-gigawatt-expansion-555k-gpus-january-2026",
    partner: null
  },
  {
    id: "celestica-hq",
    project: "Celestica AI Manufacturing HQ",
    company: "Celestica",
    location: "Toronto, Ontario, Canada",
    lat: 43.7,
    lng: -79.4,
    investment: null,
    powerMW: 50,
    powerGW: 0.05,
    gpuModel: "Manufacturing",
    size: null,
    status: "operational",
    onlineDate: "2025-01",
    statusLabel: "Online Date: 2025-01",
    description: "Major AI data center hardware manufacturer. Expanding manufacturing capacity for AI-focused data center technologies. Record 2025 performance.",
    category: "ai-independent",
    region: "north-america",
    source: null,
    partner: null
  },
  {
    id: "palantir-dc",
    project: "Palantir AI Operations Center",
    company: "Palantir",
    location: "Washington, D.C., USA",
    lat: 38.8977,
    lng: -77.0365,
    investment: null,
    powerMW: 30,
    powerGW: 0.03,
    gpuModel: "Mixed GPU",
    size: null,
    status: "operational",
    onlineDate: "2024-01",
    statusLabel: "Online Date: 2024-01",
    description: "AI operations infrastructure supporting government and enterprise AI deployments. Focus on sovereign AI and defense applications. Nuclear energy partnerships.",
    category: "ai-independent",
    region: "north-america",
    source: null,
    partner: null
  },
  {
    id: "lumentum-hq",
    project: "Lumentum Optical AI Hub",
    company: "Lumentum",
    location: "San Jose, California, USA",
    lat: 37.3861,
    lng: -122.0839,
    investment: null,
    powerMW: 20,
    powerGW: 0.02,
    gpuModel: "Optical transceivers",
    size: null,
    status: "operational",
    onlineDate: "2024-06",
    statusLabel: "Online Date: 2024-06",
    description: "Critical optical networking infrastructure for AI data center interconnects. Shares up 300% in 2025 driven by AI demand.",
    category: "ai-independent",
    region: "north-america",
    source: null,
    partner: null
  },
  {
    id: "datavolt-oxagon",
    project: "DataVolt AI Factory Campus",
    company: "DataVolt",
    location: "NEOM Oxagon, Saudi Arabia",
    lat: 28,
    lng: 35,
    investment: null,
    powerMW: 1500,
    powerGW: 1.5,
    gpuModel: "NVIDIA Blackwell",
    size: null,
    status: "construction",
    onlineDate: "2027-01",
    statusLabel: "Under Construction (Planned Online: 2027-01)",
    description: "$5B investment. 1.5 GW AI factory campus at NEOM Oxagon. One of the largest compute sites globally. Part of Project Transcendence.",
    category: "ai-independent",
    region: "middle-east",
    source: null,
    partner: null
  },
  {
    id: "anthropic-rainier",
    project: "Anthropic Training Cluster",
    company: "Anthropic",
    location: "New Carlisle, Indiana, USA",
    lat: 41.69,
    lng: -86.2,
    investment: "$11B",
    powerMW: 1000,
    powerGW: 1,
    gpuModel: "AWS Trainium 2",
    size: "1,200 acres, 30 buildings planned",
    status: "operational",
    onlineDate: "2025-10",
    statusLabel: "Online Date: 2025-10",
    description: "Dedicated cluster within AWS Project Rainier. 1M+ Trainium 2 chips for training Claude models. First 500K chips installed Oct 2025.",
    category: "ai-independent",
    region: "north-america",
    source: "https://www.cnbc.com/2025/10/29/amazon-opens-11-billion-ai-data-center-project-rainier-in-indiana.html",
    partner: null
  },
  {
    id: "scale-dc",
    project: "Scale AI Compute Hub",
    company: "Scale AI",
    location: "San Francisco, California, USA",
    lat: 37.7749,
    lng: -122.4194,
    investment: null,
    powerMW: 30,
    powerGW: 0.03,
    gpuModel: "NVIDIA GPU",
    size: null,
    status: "operational",
    onlineDate: "2025-06",
    statusLabel: "Online Date: 2025-06",
    description: "AI data infrastructure for training data and model evaluation. Government contracts for defense AI applications.",
    category: "ai-independent",
    region: "north-america",
    source: null,
    partner: null
  },
  {
    id: "inflection-hub",
    project: "Inflection AI Hub",
    company: "Inflection AI",
    location: "Palo Alto, California, USA",
    lat: 37.4419,
    lng: -122.143,
    investment: null,
    powerMW: 50,
    powerGW: 0.05,
    gpuModel: "NVIDIA H100",
    size: null,
    status: "operational",
    onlineDate: "2025-01",
    statusLabel: "Online Date: 2025-01",
    description: "AI compute infrastructure operated by Inflection AI (now closely aligned with Microsoft). Focused on enterprise AI deployment.",
    category: "ai-independent",
    region: "north-america",
    source: null,
    partner: null
  },
  {
    id: "humain-riyadh",
    project: "HUMAIN Sovereign AI Campus",
    company: "HUMAIN (Saudi Arabia)",
    location: "Riyadh, Saudi Arabia",
    lat: 24.7136,
    lng: 46.6753,
    investment: "Multi-billion $ (part of $40B fund)",
    powerMW: 1900,
    powerGW: 1.9,
    gpuModel: "NVIDIA Blackwell",
    size: "Multiple sites",
    status: "construction",
    onlineDate: "2026-09",
    statusLabel: "Under Construction (Planned Online: 2026-09)",
    description: "Saudi sovereign AI initiative. 1.9 GW by 2030, scaling to 6.6 GW by 2034. $77B total build cost. First 100 MW live Q2 2026. 18,000 NVIDIA Blackwell GPUs initial tranche.",
    category: "sovereign",
    region: "middle-east",
    source: "https://mei.edu/report/from-crude-to-compute-building-the-gcc-ai-stack/",
    partner: "PIF, NVIDIA, AMD"
  },
  {
    id: "uk-aigz",
    project: "UK AI Growth Zone",
    company: "UK Government",
    location: "London & Multiple UK Sites",
    lat: 51.5074,
    lng: -0.1278,
    investment: null,
    powerMW: 6000,
    powerGW: 6,
    gpuModel: "Mixed",
    size: null,
    status: "planned",
    onlineDate: "2030-01",
    statusLabel: "Planned Capacity Date: 2030-01",
    description: "UK targets 6 GW AI-capable DC capacity by 2030 (3x current). AI Growth Zones with 500 MW+ each, at least one exceeding 1 GW. £31B UK-US tech partnership.",
    category: "sovereign",
    region: "europe",
    source: null,
    partner: null
  },
  {
    id: "india-adaniconnex",
    project: "AdaniConneX AI Mega Campus",
    company: "AdaniConneX (India)",
    location: "Hyderabad, India",
    lat: 17.385,
    lng: 78.4867,
    investment: null,
    powerMW: 500,
    powerGW: 0.5,
    gpuModel: "NVIDIA GPU",
    size: null,
    status: "construction",
    onlineDate: "2026-06",
    statusLabel: "Under Construction (Planned Online: 2026-06)",
    description: "India's push for sovereign AI compute. Advanced liquid cooling. Part of India's $27.2B data center market by 2032. Supports government AI initiatives.",
    category: "sovereign",
    region: "asia-pacific",
    source: null,
    partner: null
  },
  {
    id: "india-jio",
    project: "Reliance Jio AI Data Centers",
    company: "Reliance Jio (India)",
    location: "Mumbai, India",
    lat: 19.076,
    lng: 72.8777,
    investment: null,
    powerMW: 300,
    powerGW: 0.3,
    gpuModel: "NVIDIA GH200",
    size: null,
    status: "construction",
    onlineDate: "2026-03",
    statusLabel: "Under Construction (Planned Online: 2026-03)",
    description: "GPU-as-a-Service infrastructure using NVIDIA GH200 Grace Hopper Superchip and DGX Cloud. India's first large-scale generative AI platform.",
    category: "sovereign",
    region: "asia-pacific",
    source: null,
    partner: "NVIDIA"
  },
  {
    id: "indo-damac",
    project: "DAMAC Digital Jakarta",
    company: "DAMAC Digital (Indonesia)",
    location: "Jakarta, Indonesia",
    lat: -6.2088,
    lng: 106.8456,
    investment: null,
    powerMW: 300,
    powerGW: 0.3,
    gpuModel: "Mixed GPU",
    size: "Hyperscale campus",
    status: "construction",
    onlineDate: "2026-06",
    statusLabel: "Under Construction (Planned Online: 2026-06)",
    description: "$2.3B AI-ready data center. Part of DAMAC's 300 MW capacity across Asia by 2026. Supporting Indonesia's AI sovereignty goals.",
    category: "sovereign",
    region: "asia-pacific",
    source: "https://www.datacenterknowledge.com/data-center-construction/new-data-center-developments-december-2025",
    partner: null
  },
  {
    id: "canada-sovereign",
    project: "Canada Sovereign AI DC",
    company: "Government of Canada",
    location: "Ottawa Region, Canada",
    lat: 45.4215,
    lng: -75.6972,
    investment: null,
    powerMW: 200,
    powerGW: 0.2,
    gpuModel: "Mixed",
    size: null,
    status: "planned",
    onlineDate: "2027-06",
    statusLabel: "Planned Capacity Date: 2027-06",
    description: "Call for proposals closed Feb 2026 for sovereign AI DCs >100 MW. Preference for renewable energy, Indigenous participation, Canadian supply chains.",
    category: "sovereign",
    region: "north-america",
    source: null,
    partner: null
  },
  {
    id: "uae-g42",
    project: "G42 AI Compute Campus",
    company: "G42 (UAE)",
    location: "Abu Dhabi, UAE",
    lat: 24.4539,
    lng: 54.3773,
    investment: "Part of 10-sq-mile campus",
    powerMW: 500,
    powerGW: 0.5,
    gpuModel: "NVIDIA Blackwell",
    size: "10 square miles planned",
    status: "construction",
    onlineDate: "2026-09",
    statusLabel: "Under Construction (Planned Online: 2026-09)",
    description: "UAE's flagship sovereign AI infrastructure. Partnership with Microsoft. Powers Falcon LLMs and regional AI services.",
    category: "sovereign",
    region: "middle-east",
    source: "https://mei.edu/report/from-crude-to-compute-building-the-gcc-ai-stack/",
    partner: "Microsoft, NVIDIA"
  },
  {
    id: "japan-sakura",
    project: "SAKURA Internet AI DC",
    company: "SAKURA Internet (Japan)",
    location: "Osaka, Japan",
    lat: 34.6937,
    lng: 135.5023,
    investment: null,
    powerMW: 200,
    powerGW: 0.2,
    gpuModel: "NVIDIA DGX",
    size: null,
    status: "construction",
    onlineDate: "2026-06",
    statusLabel: "Under Construction (Planned Online: 2026-06)",
    description: "Japan's sovereign AI cloud initiative. NVIDIA DGX SuperPOD deployment. Part of Japan's national AI infrastructure strategy.",
    category: "sovereign",
    region: "asia-pacific",
    source: null,
    partner: null
  },
  {
    id: "france-scaleway",
    project: "Scaleway AI Datacenter",
    company: "Scaleway (France)",
    location: "Paris, France",
    lat: 48.8566,
    lng: 2.3522,
    investment: "$20.7B",
    powerMW: 100,
    powerGW: 0.1,
    gpuModel: "NVIDIA H100/Blackwell",
    size: null,
    status: "operational",
    onlineDate: "2025-03",
    statusLabel: "Online Date: 2025-03",
    description: "European sovereign cloud. Hosts Mistral AI workloads. Part of France's €2.5B national AI strategy.",
    category: "sovereign",
    region: "europe",
    source: "https://www.sentisight.ai/european-countries-with-most-data-centers/",
    partner: null
  },
  {
    id: "china-mobile-harbin",
    project: "China Mobile Harbin DC",
    company: "China Mobile (China)",
    location: "Harbin, Heilongjiang, China",
    lat: 45.7,
    lng: 126.65,
    investment: null,
    powerMW: 200,
    powerGW: 0.2,
    gpuModel: "Mixed",
    size: null,
    status: "operational",
    onlineDate: "2022-01",
    statusLabel: "Online Date: 2022-01",
    description: "One of the world's largest DCs by area (663,000 sqm). 200 MW. Part of China's national AI compute infrastructure.",
    category: "sovereign",
    region: "asia-pacific",
    source: null,
    partner: null
  },
  {
    id: "stargate-lordstown",
    project: "Stargate Lordstown",
    company: "Stargate (SoftBank/OpenAI)",
    location: "Lordstown, Ohio, USA",
    lat: 41.1667,
    lng: -80.8573,
    investment: null,
    powerMW: 750,
    powerGW: 0.75,
    gpuModel: "NVIDIA GB200",
    size: null,
    status: "construction",
    onlineDate: "2026-06",
    statusLabel: "Under Construction (Planned Online: 2026-06)",
    description: "SoftBank-OpenAI advanced data center design. Broke ground 2025. On track to be operational 2026. Part of 1.5 GW SoftBank-OpenAI sites.",
    category: "stargate",
    region: "north-america",
    source: "https://openai.com/index/five-new-stargate-sites/",
    partner: "SoftBank, OpenAI"
  },
  {
    id: "stargate-milam",
    project: "Stargate Milam County",
    company: "Stargate (SB Energy)",
    location: "Milam County, Texas, USA",
    lat: 30.77,
    lng: -96.87,
    investment: null,
    powerMW: 750,
    powerGW: 0.75,
    gpuModel: "NVIDIA GB200",
    size: null,
    status: "construction",
    onlineDate: "2026-09",
    statusLabel: "Under Construction (Planned Online: 2026-09)",
    description: "Fast-build data center by SB Energy (SoftBank). Powered infrastructure for rapid deployment. Part of Stargate initiative.",
    category: "stargate",
    region: "north-america",
    source: "https://openai.com/index/five-new-stargate-sites/",
    partner: "SB Energy, OpenAI"
  },
  {
    id: "meta-elpaso",
    project: "Meta El Paso AI Campus",
    company: "Meta Platforms",
    location: "El Paso, Texas, USA",
    lat: 31.8776,
    lng: -106.3744,
    investment: "$1.5B+",
    powerMW: 1000,
    powerGW: 1,
    gpuModel: "NVIDIA Blackwell / Meta MTIA",
    size: null,
    status: "construction",
    onlineDate: "2028-01",
    statusLabel: "Under Construction (Planned Online: 2028-01)",
    description: "Meta's 29th data center, 3rd in Texas. Broke ground Oct 2025 on 1,000+ acres. Investment scaled from $1.5B to $10B in Mar 2026. Up to 5 phases of ~800,000 sqft. Closed-loop liquid cooling, near-zero operational water use. 300+ permanent jobs at full operation.",
    category: "hyperscaler",
    region: "north-america",
    source: "https://datacenters.atmeta.com/us-locations/",
    partner: "El Paso Electric"
  },
  {
    id: "crusoe-abilene",
    project: "Crusoe Abilene AI Campus",
    company: "Crusoe Energy",
    location: "Abilene, Texas, USA",
    lat: 32.4487,
    lng: -99.7331,
    investment: "$500B (overall program)",
    powerMW: 900,
    powerGW: 0.9,
    gpuModel: "NVIDIA GB200+",
    size: "4,000,000 sq ft",
    status: "construction",
    onlineDate: "2027-06",
    statusLabel: "Under Construction (Planned Online: 2027-06)",
    description: "900 MW AI campus at Lancium Clean Campus. Announced Apr 2026 for Microsoft AI workloads. Expands Stargate Site 1 (200 MW operational on same site). Direct-to-chip liquid cooling, up to 100,000 GPUs on unified fabric. 100% renewable via Lancium Smart Response.",
    category: "neocloud",
    region: "north-america",
    source: "https://openai.com/index/five-new-stargate-sites/",
    partner: "Microsoft, Lancium"
  },
  {
    id: "nscale-westvirginia",
    project: "Nscale Monarch AI Campus",
    company: "Nscale",
    location: "Mason County, West Virginia, USA",
    lat: 38.7704,
    lng: -82.0026,
    investment: null,
    powerMW: 1350,
    powerGW: 1.35,
    gpuModel: "NVIDIA Vera Rubin NVL72",
    size: null,
    status: "planned",
    onlineDate: "2028-01",
    statusLabel: "Planned Capacity Date: 2028-01",
    description: "Nscale's US flagship AI factory on 2,250 acres. Microsoft LOI for 1.35 GW of NVIDIA Vera Rubin NVL72 compute signed at GTC Mar 2026. US-first certified AI microgrid, scalable to 8 GW. Site acquired via AIPCorp/Fidelis New Energy. Carbon sequestration planned.",
    category: "neocloud",
    region: "north-america",
    source: null,
    partner: "Microsoft, NVIDIA, Caterpillar"
  },
  {
    id: "penzance-wv",
    project: "Penzance Bedington Campus",
    company: "Penzance Management",
    location: "Falling Waters, Berkeley County, West Virginia, USA",
    lat: 39.5512,
    lng: -77.9947,
    investment: null,
    powerMW: 600,
    powerGW: 0.6,
    gpuModel: null,
    size: null,
    status: "planned",
    onlineDate: "2028-06",
    statusLabel: "Planned Capacity Date: 2028-06",
    description: "West Virginia's first certified High Impact Intelligence Center. 548 acres, 1.9M sqft at full build-out. $4B investment. Hyperscaler leasing model. Announced Feb 2026. Adjacent to Northern Virginia Data Center Alley, ~1 hour from Ashburn.",
    category: "hyperscaler",
    region: "north-america",
    source: null,
    partner: null
  },
  {
    id: "gcp-westvirginia",
    project: "Google Putnam County",
    company: "Google Cloud",
    location: "Buffalo, Putnam County, West Virginia, USA",
    lat: 38.6112,
    lng: -81.9793,
    investment: null,
    powerMW: 300,
    powerGW: 0.3,
    gpuModel: "Google TPU v6",
    size: null,
    status: "planned",
    onlineDate: "2028-01",
    statusLabel: "Planned Capacity Date: 2028-01",
    description: "Google's first West Virginia campus in Buffalo, Putnam County. Certified High Impact Intelligence Center Mar 2026. 100% renewable electricity. Water replenishment target 120% by 2030. Part of Google's Appalachian corridor expansion.",
    category: "hyperscaler",
    region: "north-america",
    source: null,
    partner: null
  },
  {
    id: "gcp-wilbarger",
    project: "Google Wilbarger County",
    company: "Google Cloud",
    location: "Wilbarger County, Texas, USA",
    lat: 33.9137,
    lng: -99.1804,
    investment: "Part of $40B Texas plan",
    powerMW: 300,
    powerGW: 0.3,
    gpuModel: "Google TPU v6",
    size: null,
    status: "construction",
    onlineDate: "2027-06",
    statusLabel: "Under Construction (Planned Online: 2027-06)",
    description: "Announced Feb 2026, part of Google's $40B Texas investment. Co-located with AES clean generation — 'power-first' design. Air-cooled to eliminate operational water use. Part of 7,800+ MW of net-new Texas grid capacity contracted by Google.",
    category: "hyperscaler",
    region: "north-america",
    source: "https://www.crn.com/news/cloud/2026/google-unveils-two-new-us-data-centers-as-185-billion-commitment-gets-underway",
    partner: "AES Corporation"
  },
  {
    id: "telekom-munich",
    project: "Deutsche Telekom AI DC Munich",
    company: "Deutsche Telekom",
    location: "Munich, Germany",
    lat: 48.1351,
    lng: 11.582,
    investment: "€1B ($1.2B)",
    powerMW: 50,
    powerGW: 0.05,
    gpuModel: "NVIDIA DGX B200 / Blackwell",
    size: null,
    status: "operational",
    onlineDate: "2026-03",
    statusLabel: "Online Date: 2026-03",
    description: "€1B AI data center opened Q1 2026. 1,000+ NVIDIA DGX B200 systems, 10,000 Blackwell GPUs, 500 petaflops. Boosts Germany's national AI compute by ~50%. SAP Business Technology Platform integrated. Co-developed with NVIDIA and SAP.",
    category: "sovereign",
    region: "europe",
    source: "https://www.datacenterknowledge.com/data-center-construction/new-data-center-developments-march-2026",
    partner: "NVIDIA, SAP"
  },
  {
    id: "mistral-ecodc-sweden",
    project: "Mistral AI EcoDataCenter Sweden",
    company: "Mistral AI",
    location: "Sundsvall, Sweden",
    lat: 62.3908,
    lng: 17.3069,
    investment: null,
    powerMW: 200,
    powerGW: 0.2,
    gpuModel: "NVIDIA Vera Rubin",
    size: null,
    status: "planned",
    onlineDate: "2027-06",
    statusLabel: "Planned Capacity Date: 2027-06",
    description: "$1.4B AI data center announced Mar 2026. NVIDIA Vera Rubin GPUs for European sovereign LLM training and inference. 100% renewable hydropower. Largest dedicated AI training facility in Europe independent of US hyperscaler infrastructure.",
    category: "ai-independent",
    region: "europe",
    source: null,
    partner: "EcoDataCenter"
  },
  {
    project: "Microsoft Zaragoza Campus",
    company: "Microsoft",
    location: "Zaragoza, Spain",
    lat: 41.65,
    lng: -0.88,
    investment: "€2.9B ($3.2B)",
    powerMW: 300,
    powerGW: 0.3,
    gpuModel: null,
    size: "Not disclosed",
    status: "planned",
    onlineDate: "2027-01",
    statusLabel: "Announced (2027–2028)",
    description: "Major AI and cloud data center campus in Spain, part of Microsoft's European expansion for AI infrastructure.",
    category: "hyperscaler",
    region: "europe",
    source: "https://www.sentisight.ai/european-countries-with-most-data-centers/",
    partner: null
  },
  {
    project: "Microsoft Northern Italy",
    company: "Microsoft",
    location: "Milan, Italy",
    lat: 45.46,
    lng: 9.19,
    investment: "$4.8B",
    powerMW: 250,
    powerGW: 0.25,
    gpuModel: null,
    size: "Not disclosed",
    status: "construction",
    onlineDate: "2026-01",
    statusLabel: "Under Construction (2026–2027)",
    description: "AI and cloud infrastructure expansion in northern Italy. Part of Microsoft's multi-billion European AI commitment.",
    category: "hyperscaler",
    region: "europe",
    source: "https://www.sentisight.ai/european-countries-with-most-data-centers/",
    partner: null
  },
  {
    project: "Google Armstrong County",
    company: "Google / Alphabet",
    location: "Armstrong County, Texas, USA",
    lat: 34.96,
    lng: -101.35,
    investment: "Part of $40B Texas plan",
    powerMW: 400,
    powerGW: 0.4,
    gpuModel: null,
    size: "Not disclosed",
    status: "construction",
    onlineDate: "2026-01",
    statusLabel: "Under Construction (2026–2027)",
    description: "One of three new Google data centers in Texas announced November 2025. Part of $40B investment through 2027.",
    category: "hyperscaler",
    region: "north-america",
    source: "https://www.reuters.com/business/google-invest-40-billion-new-data-centers-texas-bloomberg-news-reports-2025-11-14/",
    partner: null
  },
  {
    project: "Google Haskell County",
    company: "Google / Alphabet",
    location: "Haskell County, Texas, USA",
    lat: 33.16,
    lng: -99.73,
    investment: "Part of $40B Texas plan",
    powerMW: 400,
    powerGW: 0.4,
    gpuModel: null,
    size: "Not disclosed",
    status: "construction",
    onlineDate: "2026-01",
    statusLabel: "Under Construction (2026–2027)",
    description: "Located in West Texas near Abilene. Part of Google's three new Texas data center announcements.",
    category: "hyperscaler",
    region: "north-america",
    source: "https://www.reuters.com/business/google-invest-40-billion-new-data-centers-texas-bloomberg-news-reports-2025-11-14/",
    partner: null
  },
  {
    project: "Google Visakhapatnam (with Adani)",
    company: "Google / Adani",
    location: "Visakhapatnam, India",
    lat: 17.69,
    lng: 83.22,
    investment: "Part of $15B India plan",
    powerMW: 1000,
    powerGW: 1,
    gpuModel: null,
    size: "600 acres",
    status: "planned",
    onlineDate: "2027-01",
    statusLabel: "Government Approved (2027–2028)",
    description: "India's largest gigawatt-scale data center campus. Built by Google subsidiary Raiden Infotech India. Part of Adani's $100B AI infrastructure plan targeting 5 GW by 2035.",
    category: "hyperscaler",
    region: "asia-pacific",
    source: "https://www.datacenterknowledge.com/data-center-construction/new-data-center-developments-march-2026",
    partner: null
  },
  {
    project: "Google Germany (€5.5B)",
    company: "Google / Alphabet",
    location: "Frankfurt area, Germany",
    lat: 50.11,
    lng: 8.68,
    investment: "€5.5B ($6.4B)",
    powerMW: 400,
    powerGW: 0.4,
    gpuModel: null,
    size: "Not disclosed",
    status: "construction",
    onlineDate: "2027-01",
    statusLabel: "Under Construction (2027)",
    description: "Infrastructure and data center expansion in Europe's largest economy. Enhances Google's AI capabilities across Europe.",
    category: "hyperscaler",
    region: "europe",
    source: "https://www.reuters.com/business/google-invest-40-billion-new-data-centers-texas-bloomberg-news-reports-2025-11-14/",
    partner: null
  },
  {
    project: "Meta Beaver Dam",
    company: "Meta",
    location: "Beaver Dam, Wisconsin, USA",
    lat: 43.46,
    lng: -88.84,
    investment: "$1B+",
    powerMW: 200,
    powerGW: 0.2,
    gpuModel: null,
    size: "700,000 sq ft",
    status: "construction",
    onlineDate: "2027-01",
    statusLabel: "Broke Ground (2027)",
    description: "Meta's 30th data center, designed to support growing AI and digital infrastructure demands.",
    category: "hyperscaler",
    region: "north-america",
    source: "https://www.datacenterknowledge.com/data-center-construction/new-data-center-developments-december-2025",
    partner: null
  },
  {
    project: "Meta Bowling Green",
    company: "Meta",
    location: "Bowling Green, Ohio, USA",
    lat: 41.375,
    lng: -83.65,
    investment: "$800M+",
    powerMW: 150,
    powerGW: 0.15,
    gpuModel: null,
    size: "Not disclosed",
    status: "construction",
    onlineDate: "2027-01",
    statusLabel: "Broke Ground (2025) (2027)",
    description: "1,000+ skilled trade workers at peak construction. ~100 operational jobs once completed.",
    category: "hyperscaler",
    region: "north-america",
    source: "https://datacenters.atmeta.com/us-locations/",
    partner: null
  },
  {
    project: "AWS Northern Indiana Expansion",
    company: "Amazon / AWS",
    location: "Northern Indiana, USA",
    lat: 41.6,
    lng: -86.25,
    investment: "$15B",
    powerMW: 2400,
    powerGW: 2.4,
    gpuModel: null,
    size: "Multiple campuses",
    status: "planned",
    onlineDate: null,
    statusLabel: "Announced (Multi-year buildout)",
    description: "Additional $15B beyond the $11B Project Rainier. Adds 2.4 GW capacity. Energy agreement with NIPSCO expected to provide ~$1B in savings to Indiana residents. 1,100 new jobs.",
    category: "hyperscaler",
    region: "north-america",
    source: "https://www.aboutamazon.com/news/company-news/amazon-15-billion-indiana-data-centers",
    partner: null
  },
  {
    project: "xAI Saudi Arabia DC",
    company: "xAI / HUMAIN",
    location: "Riyadh, Saudi Arabia",
    lat: 24.71,
    lng: 46.67,
    investment: "Not disclosed",
    powerMW: 500,
    powerGW: 0.5,
    gpuModel: null,
    size: "Not disclosed",
    status: "planned",
    onlineDate: null,
    statusLabel: "Announced (TBD)",
    description: "Collaboration with HUMAIN (Saudi sovereign AI). Will utilize NVIDIA hardware and systems. Located outside Riyadh.",
    category: "neocloud",
    region: "middle-east",
    source: "https://www.datacenterknowledge.com/data-center-construction/new-data-center-developments-december-2025",
    partner: null
  },
  {
    project: "Project Horizon",
    company: "CoreWeave / Poolside",
    location: "West Texas, USA",
    lat: 31.9,
    lng: -102.1,
    investment: "Multi-billion $",
    powerMW: 2000,
    powerGW: 2,
    gpuModel: null,
    size: "Not disclosed",
    status: "construction",
    onlineDate: "2020-01",
    statusLabel: "Planning / Early Construction (Phased through late 2020s)",
    description: "Massive 2 GW campus built in 8 phases. Will generate its own power. Partnership with Poolside for NVIDIA GB300 NV72 systems with 40,000+ GPUs.",
    category: "neocloud",
    region: "north-america",
    source: "https://finance.yahoo.com/news/coreweave-building-massive-data-center-140002009.html",
    partner: null
  },
  {
    project: "Anthropic / FluidStack — New York",
    company: "Anthropic / FluidStack",
    location: "New York, USA",
    lat: 42.65,
    lng: -73.75,
    investment: "Part of $50B plan",
    powerMW: 500,
    powerGW: 0.5,
    gpuModel: null,
    size: "Not disclosed",
    status: "planned",
    onlineDate: "2026-01",
    statusLabel: "Announced (2026–2028)",
    description: "Second initial site under Anthropic's $50B data center investment with FluidStack. Additional US sites expected to follow.",
    category: "neocloud",
    region: "north-america",
    source: "https://www.datacenterknowledge.com/data-center-construction/new-data-center-developments-december-2025",
    partner: null
  },
  {
    project: "AVAIO Digital Leo",
    company: "AVAIO Digital",
    location: "Little Rock, Arkansas, USA",
    lat: 34.75,
    lng: -92.29,
    investment: "$6B (initial), $21B (full)",
    powerMW: 1000,
    powerGW: 1,
    gpuModel: null,
    size: "760 acres",
    status: "construction",
    onlineDate: "2027-01",
    statusLabel: "Broke Ground (early 2026) (150 MW energized June 2027)",
    description: "Named after constellation Leo. Multi-phase campus. Largest investment in Arkansas state history. 500+ permanent jobs. Contracted with Entergy Arkansas.",
    category: "ai-independent",
    region: "north-america",
    source: "https://www.avaiodigital.com/updates/avaio-digital-announces-new-large-scale-ai-ready-data-center-and-power-campus-in-little-rock-arkansas",
    partner: null
  },
  {
    project: "Compass Meridian",
    company: "Compass Datacenters",
    location: "Meridian, Mississippi, USA",
    lat: 32.36,
    lng: -88.7,
    investment: "$10B",
    powerMW: 320,
    powerGW: 0.32,
    gpuModel: null,
    size: "8 buildings, 250,000 sq ft each",
    status: "construction",
    onlineDate: "2033-01",
    statusLabel: "Under Construction (Full completion 2033)",
    description: "Eight-building campus. Contractor: Eutaw Construction. Long-term phased build-out in Mississippi.",
    category: "ai-independent",
    region: "north-america",
    source: "https://www.equipmentworld.com/market-pulse/article/15816534/data-center-construction-boom-to-grow-in-2026",
    partner: null
  },
  {
    project: "Energy Storage Solutions NC Campus",
    company: "Energy Storage Solutions",
    location: "Rocky Mount, North Carolina, USA",
    lat: 35.94,
    lng: -77.79,
    investment: "$19.2B",
    powerMW: 900,
    powerGW: 0.9,
    gpuModel: null,
    size: "300 acres",
    status: "planned",
    onlineDate: "2026-01",
    statusLabel: "Zoning Approved (Construction begins Q1 2026)",
    description: "Massive data center and energy storage campus. County commissioners approved data center zoning. Twin project also planned for Fayetteville.",
    category: "ai-independent",
    region: "north-america",
    source: "https://www.datacenterknowledge.com/data-center-construction/new-data-center-developments-december-2025",
    partner: null
  },
  {
    project: "Powhatan County DC",
    company: "JLL / Dominion Energy",
    location: "Powhatan County, Virginia, USA",
    lat: 37.55,
    lng: -77.92,
    investment: "Not disclosed",
    powerMW: 365,
    powerGW: 0.365,
    gpuModel: null,
    size: "180 acres",
    status: "planned",
    onlineDate: null,
    statusLabel: "Approved (TBD)",
    description: "Unanimously approved by County Board. Powered by Dominion Energy with initial 365 MW deployment.",
    category: "ai-independent",
    region: "north-america",
    source: "https://www.datacenterknowledge.com/data-center-construction/new-data-center-developments-december-2025",
    partner: null
  },
  {
    project: "Mistral AI / EcoDataCenter Sweden",
    company: "Mistral AI / EcoDataCenter",
    location: "Sweden",
    lat: 59.33,
    lng: 18.07,
    investment: "$1.4B",
    powerMW: 200,
    powerGW: 0.2,
    gpuModel: null,
    size: "Not disclosed",
    status: "planned",
    onlineDate: "2027-01",
    statusLabel: "Announced (Launch 2027)",
    description: "AI-focused data center employing NVIDIA Vera Rubin GPUs. French AI firm partnering with Swedish green data center operator.",
    category: "sovereign",
    region: "europe",
    source: "https://www.datacenterknowledge.com/data-center-construction/new-data-center-developments-march-2026",
    partner: null
  },
  {
    project: "Brookfield AI DC Stockholm",
    company: "Brookfield Infrastructure",
    location: "Stockholm, Sweden",
    lat: 59.35,
    lng: 18.1,
    investment: "Up to $10B",
    powerMW: 750,
    powerGW: 0.75,
    gpuModel: null,
    size: "Not disclosed",
    status: "planned",
    onlineDate: null,
    statusLabel: "Under Development (Phased)",
    description: "One of Europe's largest infrastructure investments. Leverages Nordic cool climate for free cooling and abundant renewable hydropower.",
    category: "ai-independent",
    region: "europe",
    source: "https://www.sentisight.ai/european-countries-with-most-data-centers/",
    partner: null
  },
  {
    project: "CDC Marsden Park Campus",
    company: "CDC Data Centers",
    location: "Marsden Park, NSW, Australia",
    lat: -33.69,
    lng: 150.84,
    investment: "$3.1B",
    powerMW: 300,
    powerGW: 0.3,
    gpuModel: null,
    size: "Southern hemisphere's largest",
    status: "planned",
    onlineDate: null,
    statusLabel: "Approved (TBD)",
    description: "NSW-approved campus. Will be the southern hemisphere's largest data center project.",
    category: "ai-independent",
    region: "asia-pacific",
    source: "https://www.datacenterknowledge.com/data-center-construction/new-data-center-developments-december-2025",
    partner: null
  },
  {
    project: "CDC Brooklyn Victoria",
    company: "CDC Data Centers",
    location: "Brooklyn, Victoria, Australia",
    lat: -37.81,
    lng: 144.84,
    investment: "$4B+",
    powerMW: 200,
    powerGW: 0.2,
    gpuModel: null,
    size: "2 facilities + 3rd planned, 2nd campus at Laverton North",
    status: "operational",
    onlineDate: null,
    statusLabel: "Partially Operational (Expanding)",
    description: "Two operational facilities with a third planned. Second campus at Laverton North in development.",
    category: "ai-independent",
    region: "asia-pacific",
    source: "https://www.datacenterknowledge.com/data-center-construction/new-data-center-developments-march-2026",
    partner: null
  },
  {
    project: "Kinh Bac / AIC Ho Chi Minh City",
    company: "Kinh Bac / Accelerated Infrastructure Capital",
    location: "Ho Chi Minh City, Vietnam",
    lat: 10.82,
    lng: 106.63,
    investment: "Not disclosed",
    powerMW: 200,
    powerGW: 0.2,
    gpuModel: null,
    size: "Not disclosed",
    status: "planned",
    onlineDate: null,
    statusLabel: "MoA Signed (TBD)",
    description: "Joint venture with VietinBank. AI data center in Vietnam's largest city.",
    category: "ai-independent",
    region: "asia-pacific",
    source: "https://www.datacenterknowledge.com/data-center-construction/new-data-center-developments-december-2025",
    partner: null
  },
  {
    project: "DayOne / Amata Thailand 1 GW",
    company: "DayOne / Amata Corporation",
    location: "Eastern Thailand",
    lat: 13.36,
    lng: 101,
    investment: "Not disclosed",
    powerMW: 1000,
    powerGW: 1,
    gpuModel: null,
    size: "Not disclosed",
    status: "planned",
    onlineDate: null,
    statusLabel: "MoA Signed (Phased)",
    description: "Thailand's first 1 GW power platform for data centers. 16 additional acres allotted to expand CTP1 site to 300 MW.",
    category: "ai-independent",
    region: "asia-pacific",
    source: "https://www.datacenterknowledge.com/data-center-construction/new-data-center-developments-december-2025",
    partner: null
  },
  {
    project: "Yotta Greater Noida AI Supercluster",
    company: "Yotta",
    location: "Greater Noida, India",
    lat: 28.47,
    lng: 77.5,
    investment: "$2B+",
    powerMW: 300,
    powerGW: 0.3,
    gpuModel: null,
    size: "Not disclosed",
    status: "planned",
    onlineDate: "2026-01",
    statusLabel: "Under Development (2026–2027)",
    description: "One of Asia's largest AI superclusters. Includes capacity from Navi Mumbai campus. Seeking $1.2B from investors ahead of IPO.",
    category: "ai-independent",
    region: "asia-pacific",
    source: "https://www.datacenterknowledge.com/data-center-construction/new-data-center-developments-march-2026",
    partner: null
  },
  {
    project: "Hyundai AI Hub Gunsan",
    company: "Hyundai Motor Group",
    location: "Gunsan City, South Korea",
    lat: 35.98,
    lng: 126.72,
    investment: "$6.3B",
    powerMW: 300,
    powerGW: 0.3,
    gpuModel: null,
    size: "Saemangeum innovation hub",
    status: "planned",
    onlineDate: null,
    statusLabel: "Announced (TBD)",
    description: "Innovation hub spanning AI data center, robotics manufacturing, and hydrogen/solar energy generation.",
    category: "sovereign",
    region: "asia-pacific",
    source: "https://www.datacenterknowledge.com/data-center-construction/new-data-center-developments-march-2026",
    partner: null
  },
  {
    project: "Kazakhstan Ekibastuz Campus",
    company: "Government of Kazakhstan",
    location: "Ekibastuz, Kazakhstan",
    lat: 51.72,
    lng: 75.32,
    investment: "Not disclosed",
    powerMW: 1000,
    powerGW: 1,
    gpuModel: null,
    size: "Central Asia's largest",
    status: "planned",
    onlineDate: null,
    statusLabel: "Planned (TBD)",
    description: "Central Asia's largest planned data center campus. Leverages abundant energy resources in Ekibastuz.",
    category: "sovereign",
    region: "asia-pacific",
    source: "https://www.datacenterknowledge.com/data-center-construction/new-data-center-developments-march-2026",
    partner: null
  },
  {
    project: "OpenAI / Samsung / SK Telecom Seoul",
    company: "OpenAI / Samsung SDS / SK Telecom",
    location: "South Korea",
    lat: 37.55,
    lng: 127,
    investment: "Not disclosed",
    powerMW: 20,
    powerGW: 0.02,
    gpuModel: null,
    size: "Not disclosed",
    status: "construction",
    onlineDate: "2026-01",
    statusLabel: "Construction began Mar 2026 (2026–2027)",
    description: "Joint construction by OpenAI, Samsung SDS, and SK Telecom. Announced by Science Minister Bae Kyung-hoon.",
    category: "sovereign",
    region: "asia-pacific",
    source: "https://www.datacenterknowledge.com/data-center-construction/new-data-center-developments-march-2026",
    partner: null
  },
  {
    project: "Rio AI City",
    company: "Goldman Sachs-backed",
    location: "Rio de Janeiro, Brazil",
    lat: -22.91,
    lng: -43.17,
    investment: "Multi-billion $",
    powerMW: 443,
    powerGW: 0.443,
    gpuModel: null,
    size: "Not disclosed",
    status: "planned",
    onlineDate: "2031-01",
    statusLabel: "Under Development (Phased through 2031)",
    description: "Goldman Sachs-backed project. Will increase Latin America AI data center capacity from 443 MW (2026) to 1.6 GW by 2031.",
    category: "ai-independent",
    region: "latam",
    source: "https://www.abiresearch.com/blog/data-centers-by-region-size-company",
    partner: null
  },
  {
    project: "Stargate UAE",
    company: "OpenAI / G42 / NVIDIA",
    location: "Abu Dhabi, UAE",
    lat: 24.45,
    lng: 54.65,
    investment: "Part of 10-sq-mile campus",
    powerMW: 5000,
    powerGW: 5,
    gpuModel: null,
    size: "10 square miles planned",
    status: "planned",
    onlineDate: "2030-01",
    statusLabel: "Construction Planning (Phased through 2030)",
    description: "G42 building Stargate infrastructure in Abu Dhabi. Part of US-UAE AI Acceleration Partnership. OpenAI providing ChatGPT Plus nationwide to UAE residents.",
    category: "stargate",
    region: "middle-east",
    source: "https://mei.edu/report/from-crude-to-compute-building-the-gcc-ai-stack/",
    partner: "OpenAI, G42, NVIDIA"
  },
  {
    project: "Google Pine Island",
    company: "Google / Alphabet",
    location: "Pine Island, Minnesota, USA",
    lat: 44.2,
    lng: -92.65,
    investment: "$1B+",
    powerMW: 300,
    powerGW: 0.3,
    gpuModel: null,
    size: "Not disclosed",
    status: "construction",
    onlineDate: "2027-01",
    statusLabel: "Under Construction (Expected 2027)",
    description: "Powered by new wind, solar, and battery energy via Xcel Energy contract. Supports AI and cloud capability expansion.",
    category: "hyperscaler",
    region: "north-america",
    source: "https://www.crn.com/news/cloud/2026/google-unveils-two-new-us-data-centers-as-185-billion-commitment-gets-underway",
    partner: null
  },
  {
    project: "Anthropic / FluidStack — Texas",
    company: "Anthropic / FluidStack",
    location: "Texas, USA",
    lat: 32.78,
    lng: -96.8,
    investment: "Part of $50B plan",
    powerMW: 500,
    powerGW: 0.5,
    gpuModel: null,
    size: "Not disclosed",
    status: "planned",
    onlineDate: "2026-01",
    statusLabel: "Announced (2026–2028)",
    description: "Part of Anthropic's $50B plan to build US data centers with UK-based FluidStack. Will create 800 permanent jobs and 2,000 construction roles across all sites.",
    category: "neocloud",
    region: "north-america",
    source: "https://www.datacenterknowledge.com/data-center-construction/new-data-center-developments-december-2025",
    partner: null
  }
];

// Timeline events with annotations
const TIMELINE_EVENTS = [
  {
    "date": "2025-01-21",
    "title": "Stargate Project Announced",
    "category": "stargate",
    "description": "OpenAI, SoftBank, Oracle, and MGX announce $500B Stargate AI infrastructure project at the White House with President Trump. Arm, Microsoft, and NVIDIA as technology partners.",
    "impact": "high",
    "companies": [
      "OpenAI",
      "SoftBank",
      "Oracle",
      "MGX",
      "NVIDIA",
      "Arm",
      "Microsoft"
    ]
  },
  {
    "date": "2025-06-01",
    "title": "Stargate Abilene Goes Live",
    "category": "stargate",
    "description": "First NVIDIA GB200 racks delivered at flagship Stargate campus in Abilene, Texas on Oracle Cloud Infrastructure.",
    "impact": "high",
    "companies": [
      "Oracle",
      "OpenAI",
      "NVIDIA"
    ]
  },
  {
    "date": "2025-07-01",
    "title": "Oracle-OpenAI 4.5 GW Agreement",
    "category": "stargate",
    "description": "Oracle and OpenAI enter agreement to develop up to 4.5 GW of additional Stargate capacity. Partnership exceeds $300B over five years.",
    "impact": "high",
    "companies": [
      "Oracle",
      "OpenAI"
    ]
  },
  {
    "date": "2025-07-31",
    "title": "Stargate Norway Announced",
    "category": "stargate",
    "description": "Nscale, Aker ASA, and OpenAI launch Stargate Norway in Narvik. OpenAI's first data centre in Europe. 230 MW initial, 290 MW expansion. 100,000 NVIDIA GPUs by end 2026.",
    "impact": "high",
    "companies": [
      "Nscale",
      "Aker ASA",
      "OpenAI",
      "NVIDIA"
    ]
  },
  {
    "date": "2025-08-21",
    "title": "Lambda AI Factory Chicago",
    "category": "neocloud",
    "description": "Lambda and EdgeConneX announce 30+ MW AI factory infrastructure in Chicago and Atlanta. Hybrid cooling supporting 600+ kW/rack densities.",
    "impact": "medium",
    "companies": [
      "Lambda Labs",
      "EdgeConneX"
    ]
  },
  {
    "date": "2025-09-17",
    "title": "Nscale-Aker $6.2B Microsoft Deal",
    "category": "neocloud",
    "description": "Nscale and Aker sign binding $6.2B five-year agreement with Microsoft for AI compute capacity at Narvik, Norway. One of the largest GPU deployments globally.",
    "impact": "high",
    "companies": [
      "Nscale",
      "Aker ASA",
      "Microsoft"
    ]
  },
  {
    "date": "2025-09-18",
    "title": "Microsoft Fairwater 1 Opens",
    "category": "hyperscaler",
    "description": "Microsoft opens Fairwater in Mount Pleasant, Wisconsin — billed as the world's most powerful AI datacenter. $7.3B investment. Fiber cable to circle Earth 4 times.",
    "impact": "high",
    "companies": [
      "Microsoft Azure"
    ]
  },
  {
    "date": "2025-09-23",
    "title": "Stargate Expands to 7 GW",
    "category": "stargate",
    "description": "OpenAI, Oracle, and SoftBank unveil 5 new Stargate sites (Texas, New Mexico, Ohio, Midwest). Nearly 7 GW planned capacity, $400B+ investment. Ahead of schedule.",
    "impact": "high",
    "companies": [
      "OpenAI",
      "Oracle",
      "SoftBank"
    ]
  },
  {
    "date": "2025-10-01",
    "title": "Stargate Partners Confirmed",
    "category": "stargate",
    "description": "Reuters confirms key Stargate stakeholders: OpenAI, SoftBank, Oracle, Arm Holdings, MGX, Crusoe, Nscale Global Holdings, and Aker ASA.",
    "impact": "medium",
    "companies": [
      "OpenAI",
      "SoftBank",
      "Oracle",
      "Arm Holdings",
      "Crusoe",
      "Nscale",
      "Aker ASA"
    ]
  },
  {
    "date": "2025-10-29",
    "title": "AWS Project Rainier Opens",
    "category": "hyperscaler",
    "description": "Amazon opens $11B AI data center in Indiana dedicated to Anthropic. 1,200 acres, 7 buildings operational. Will scale to 30 buildings and 2.25 GW.",
    "impact": "high",
    "companies": [
      "Amazon Web Services",
      "Anthropic"
    ]
  },
  {
    "date": "2025-11-16",
    "title": "Microsoft Fairwater 2 Atlanta",
    "category": "hyperscaler",
    "description": "Microsoft Fairwater 2 opens in Atlanta, Georgia. Connected to Wisconsin via AI Wide Area Network. Combined network exceeds 2 GW. World's most powerful AI facility.",
    "impact": "high",
    "companies": [
      "Microsoft Azure"
    ]
  },
  {
    "date": "2025-12-11",
    "title": "Big Tech Power Strategy Shift",
    "category": "hyperscaler",
    "description": "Reuters reports Big Tech adopts 'all of the above' power strategy. US data center power supply reaches 61.8 GW, projected 134.4 GW by 2030. Gas + nuclear + renewables.",
    "impact": "medium",
    "companies": [
      "Meta",
      "Google",
      "Microsoft",
      "Amazon"
    ]
  },
  {
    "date": "2025-12-24",
    "title": "AI Infra Stocks Outperform NVIDIA",
    "category": "semiconductor",
    "description": "CNBC reports Celestica, Lumentum, and Seagate AI infrastructure stocks beat NVIDIA returns in 2025. Celestica up ~300%. Data center buildout beneficiaries surge.",
    "impact": "medium",
    "companies": [
      "Celestica",
      "Lumentum"
    ]
  },
  {
    "date": "2025-12-30",
    "title": "xAI Colossus Hits 2 GW",
    "category": "ai-independent",
    "description": "Elon Musk announces xAI purchases third building 'MACROHARDRR', expanding Colossus to 2 GW. 555,000+ NVIDIA GPUs ($18B). World's largest single-site AI installation.",
    "impact": "high",
    "companies": [
      "xAI",
      "NVIDIA"
    ]
  },
  {
    "date": "2026-01-12",
    "title": "Nebius Plans 1.1 GW Kansas City Campus",
    "category": "neocloud",
    "description": "Nebius announces plans for 800MW+ data center campus outside Kansas City. Expansion to ~1.1 GW by December 2029. Construction starts 2026.",
    "impact": "high",
    "companies": [
      "Nebius"
    ]
  },
  {
    "date": "2026-01-22",
    "title": "Applied Digital Delta Forge Groundbreaking",
    "category": "neocloud",
    "description": "Applied Digital breaks ground on Delta Forge 1, a 430 MW AI Factory campus. Two 150 MW buildings across 500+ acres. Operations expected mid-2027.",
    "impact": "medium",
    "companies": [
      "Applied Digital"
    ]
  },
  {
    "date": "2026-02-03",
    "title": "Saudi HUMAIN Targets 6.6 GW",
    "category": "sovereign",
    "description": "Saudi Arabia's HUMAIN plans 1.9 GW by 2030, scaling to 6.6 GW by 2034. $77B build cost. NEOM potentially redesignated as data center hub. DataVolt $5B campus.",
    "impact": "high",
    "companies": [
      "HUMAIN",
      "DataVolt",
      "NVIDIA",
      "AMD"
    ]
  },
  {
    "date": "2026-03-03",
    "title": "Nebius Gigawatt Factory Approved",
    "category": "neocloud",
    "description": "Independence, Missouri City Council approves Nebius's 1.2 GW AI factory. Largest US AI factory for Nebius. Connected to municipal utility. No residential rate impact.",
    "impact": "high",
    "companies": [
      "Nebius"
    ]
  },
  {
    "date": "2026-03-03",
    "title": "CoreWeave Targets 5 GW More",
    "category": "neocloud",
    "description": "CoreWeave announces plans to add 5 GW more capacity by 2030. Ended 2025 with 850 MW across 43 DCs. CapEx expected to double in 2026. Over 3 GW contracted.",
    "impact": "high",
    "companies": [
      "CoreWeave"
    ]
  },
  {
    "date": "2026-03-17",
    "title": "Google 2.7 GW Detroit Campus",
    "category": "hyperscaler",
    "description": "Google partners with DTE Energy for 2.7 GW of new resources in suburban Detroit. Includes 1.6 GW solar, 400 MW storage, 300 MW clean resources, 50 MW long-duration storage.",
    "impact": "high",
    "companies": [
      "Google Cloud"
    ]
  },
  {
    "date": "2026-03-22",
    "title": "Meta-Nebius $27B Infrastructure Deal",
    "category": "neocloud",
    "description": "Meta commits $27B to Nebius for AI infrastructure over 5 years. Includes $12B of NVIDIA Vera Rubin chip capacity from 2027. Deal value exceeds Nebius's prior market valuation. Cements Nebius as leading neocloud alongside CoreWeave.",
    "impact": "high",
    "companies": [
      "Meta Platforms",
      "Nebius",
      "NVIDIA"
    ]
  },
  {
    "date": "2026-03-31",
    "title": "Nebius 310 MW Finland AI Factory",
    "category": "neocloud",
    "description": "Nebius announces 310 MW AI data center in Lappeenranta, Finland — its largest outside the US. $10B+ estimated value. Built by Polarnode. One of Europe's largest AI-dedicated facilities. Covers ~10% of Nebius's 3 GW target.",
    "impact": "high",
    "companies": [
      "Nebius",
      "Polarnode"
    ]
  },
  {
    "date": "2026-03-25",
    "title": "23 GW Under Construction Globally",
    "category": "hyperscaler",
    "description": "BloombergNEF reports 23+ GW of data center capacity under construction at 831 sites. 75% in the US. Top 14 operators' CapEx nears $750B in 2026.",
    "impact": "high",
    "companies": [
      "Multiple"
    ]
  },
  {
    "date": "2026-03-27",
    "title": "Meta Orders 10 Power Plants",
    "category": "hyperscaler",
    "description": "Meta orders 10 gas power plants (7.5 GW) from Entergy for Hyperion campus in Louisiana. Plus 2.5 GW renewables. 30%+ increase to Louisiana's entire grid capacity.",
    "impact": "high",
    "companies": [
      "Meta Platforms",
      "Entergy"
    ]
  },
  {
    "date": "2026-03-26",
    "title": "Meta El Paso Scaled to $10B / 1 GW",
    "category": "hyperscaler",
    "description": "Meta confirms El Paso campus grows from $1.5B to $10B investment and scales to 1 GW capacity by 2028. Meta's 29th DC globally. Closed-loop liquid cooling, zero operational water use. Part of Meta's ~30-DC global expansion wave.",
    "impact": "high",
    "companies": [
      "Meta Platforms"
    ]
  },
  {
    "date": "2026-03-16",
    "title": "Nscale West Virginia 1.35 GW Microsoft Deal",
    "category": "neocloud",
    "description": "At NVIDIA GTC 2026, Nscale signs Microsoft LOI for 1.35 GW of NVIDIA Vera Rubin NVL72 compute at Monarch Campus, Mason County, West Virginia. Site scalable to 8 GW. US-first AI microgrid certification. Nscale acquires AIPCorp for site control.",
    "impact": "high",
    "companies": [
      "Nscale",
      "Microsoft",
      "NVIDIA"
    ]
  },
  {
    "date": "2026-03-01",
    "title": "Deutsche Telekom / NVIDIA Munich AI DC Opens",
    "category": "sovereign",
    "description": "Deutsche Telekom and NVIDIA open €1B AI data center in Munich — one of Europe's largest at launch. 10,000 Blackwell GPUs, 500 petaflops. Boosts Germany's national AI compute by ~50%. SAP Business Technology Platform integrated.",
    "impact": "high",
    "companies": [
      "Deutsche Telekom",
      "NVIDIA",
      "SAP"
    ]
  },
  {
    "date": "2026-02-26",
    "title": "Penzance $4B West Virginia AI Campus",
    "category": "hyperscaler",
    "description": "Penzance Management announces 548-acre, 600 MW Bedington Campus in Berkeley County, WV — state's first certified High Impact Intelligence Center. $4B investment. Hyperscaler leasing model. Close to Northern Virginia Data Center Alley.",
    "impact": "medium",
    "companies": [
      "Penzance Management"
    ]
  },
  {
    "date": "2026-02-24",
    "title": "Google Wilbarger County TX — Power-First AI DC",
    "category": "hyperscaler",
    "description": "Google announces AI data center in Wilbarger County, Texas, co-located with AES clean generation. Air-cooled design eliminates operational water use. Part of Google's $40B Texas investment through 2027, covering 7,800+ MW of new grid capacity.",
    "impact": "medium",
    "companies": [
      "Google Cloud",
      "AES Corporation"
    ]
  },
  {
    "date": "2026-03-27",
    "title": "Google West Virginia AI Campus (Putnam County)",
    "category": "hyperscaler",
    "description": "Governor Morrisey confirms Google will build a data center in Buffalo, Putnam County, WV — state's second certified High Impact Intelligence Center. 100% renewable. Part of Google's Appalachian corridor expansion alongside Texas and Midwest sites.",
    "impact": "medium",
    "companies": [
      "Google Cloud"
    ]
  },
  {
    "date": "2026-04-01",
    "title": "Crusoe Abilene 900 MW Microsoft Campus",
    "category": "neocloud",
    "description": "Crusoe announces 900 MW AI data center campus at Lancium Clean Campus, Abilene TX for Microsoft workloads. Expands Stargate Site 1 footprint. Direct-to-chip liquid cooling, 100,000 GPUs on unified fabric. 100% renewable via Lancium Smart Response.",
    "impact": "high",
    "companies": [
      "Crusoe Energy",
      "Microsoft",
      "Lancium"
    ]
  },
  {
    "date": "2026-03-01",
    "title": "Mistral AI / EcoDataCenter $1.4B Sweden AI Factory",
    "category": "ai-independent",
    "description": "Mistral AI and EcoDataCenter announce $1.4B AI data center in Sundsvall, Sweden, using NVIDIA Vera Rubin GPUs. 100% renewable hydropower. Largest sovereign European AI training facility; targets LLM training independent of US hyperscaler infrastructure.",
    "impact": "medium",
    "companies": [
      "Mistral AI",
      "EcoDataCenter",
      "NVIDIA"
    ]
  }
];

// Company metadata for color coding and display
const COMPANY_CATEGORIES = {
  "hyperscaler": {
    "label": "Hyperscalers",
    "color": "#3b82f6",
    "companies": [
      "Amazon Web Services",
      "Microsoft Azure",
      "Google Cloud",
      "Meta Platforms",
      "Oracle Cloud",
      "Alibaba Cloud",
      "IBM Cloud",
      "Huawei",
      "Penzance Management",
      "Cologix"
    ]
  },
  "neocloud": {
    "label": "Neoclouds",
    "color": "#f59e0b",
    "companies": [
      "Nebius",
      "CoreWeave",
      "IREN",
      "Applied Digital",
      "Lambda Labs",
      "Nscale",
      "Mega Or/Mega DC",
      "Crusoe Energy",
      "Civo",
      "Vultr"
    ]
  },
  "ai-independent": {
    "label": "AI Independent",
    "color": "#8b5cf6",
    "companies": [
      "xAI",
      "Celestica",
      "Palantir",
      "Lumentum",
      "DataVolt",
      "Anthropic",
      "Scale AI",
      "Inflection AI",
      "Mistral AI"
    ]
  },
  "sovereign": {
    "label": "Sovereign/Gov",
    "color": "#10b981",
    "companies": [
      "HUMAIN",
      "UK Government",
      "AdaniConneX",
      "Reliance Jio",
      "DAMAC Digital",
      "Government of Canada",
      "G42",
      "SAKURA Internet",
      "Scaleway",
      "China Mobile",
      "Deutsche Telekom"
    ]
  },
  "stargate": {
    "label": "Stargate Project",
    "color": "#ef4444",
    "companies": [
      "Stargate",
      "OpenAI",
      "SoftBank",
      "Oracle"
    ]
  }
};

// Status colors
const STATUS_CONFIG = {
  "operational": {
    "label": "Operational",
    "color": "#22c55e",
    "icon": "●"
  },
  "construction": {
    "label": "Under Construction",
    "color": "#f59e0b",
    "icon": "◐"
  },
  "planned": {
    "label": "Planned",
    "color": "#6366f1",
    "icon": "○"
  }
};

// Semiconductor companies (for info display, not mapped as DCs)
const SEMICONDUCTOR_COMPANIES = [
  {
    "name": "NVIDIA",
    "ticker": "NVDA",
    "role": "GPU design & AI accelerators. Powers 90%+ of AI training worldwide."
  },
  {
    "name": "TSMC",
    "ticker": "TSM",
    "role": "Fabricates chips for NVIDIA, AMD, Apple, and most AI hardware."
  },
  {
    "name": "ASML Holding",
    "ticker": "ASML",
    "role": "Sole supplier of EUV lithography machines. Enables advanced chip manufacturing."
  },
  {
    "name": "Broadcom",
    "ticker": "AVGO",
    "role": "Custom AI accelerators, networking chips, and data center connectivity."
  },
  {
    "name": "AMD",
    "ticker": "AMD",
    "role": "MI300X/MI400 AI GPUs. Growing data center AI market share. $10B Saudi deal."
  },
  {
    "name": "Micron Technology",
    "ticker": "MU",
    "role": "HBM3E memory for AI GPUs. Critical component in every AI accelerator."
  },
  {
    "name": "Applied Materials",
    "ticker": "AMAT",
    "role": "Semiconductor manufacturing equipment for AI chip fabs."
  },
  {
    "name": "Arm Holdings",
    "ticker": "ARM",
    "role": "CPU architecture licensing. Stargate technology partner. Powers efficient AI inference."
  },
  {
    "name": "Marvell",
    "ticker": "MRVL",
    "role": "Custom AI silicon, data center networking, and storage accelerators."
  },
  {
    "name": "SK Hynix",
    "ticker": "000660.KS",
    "role": "HBM memory leader alongside Micron. Primary supplier to NVIDIA."
  },
  {
    "name": "Samsung Electronics",
    "ticker": "005930.KS",
    "role": "Memory (HBM, DRAM) and advanced chip foundry services."
  },
  {
    "name": "Intel Corporation",
    "ticker": "INTC",
    "role": "Gaudi AI accelerators and foundry services. Restructuring for AI era."
  }
];

